// English source text is a UI lookup key, never a config identifier.
{" (2 real + prediction)", "（2 层真实推理 + 预测）"},
{" pass(es)", " 层"},
{" pass(es) configured", " 层（配置值）"},
{" pass(es) requested", " 层（请求值）"},
{"%s CPU: %s", "%s CPU：%s"},
{"%s is active, but not currently used by the game\nPlease enter the game", "%s 已加载，但游戏暂未使用，请进入实际游戏场景。"},
{"%ux%u -> %ux%u | frame %llu", "%ux%u -> %ux%u | 帧 %llu"},
{"%zu. %s -- not read yet", "%zu. %s — 尚未读取"},
{"(Active: %d)", "（当前：%d）"},
{"(Current sharpness: %.3f)", "（当前锐化：%.3f）"},
{"(Current sharpness: disabled)", "（当前锐化：已禁用）"},
{"(Currently following cursor)", "（正在跟随光标）"},
{"(Failed to hook)", "（接管失败）"},
{"(ini has NR slots = 1: single-slot mode, not selectable here)", "（INI 中 NR 槽位数为 1；单槽模式不在此菜单中提供）"},
{"(the scan is only watching -- the white point above comes from somewhere else)", "（扫描仅供观察，当前参考白使用其他来源）"},
{"-1 follows local structure; 0 reduces skin structure independently.\nThis is not a skin-colour/tone off switch. Use the final skin/scene controls below for that.", "-1 跟随局部结构，0 可独立降低皮肤结构。这不是肤色或色调开关，相关控制在下方最终效果中。"},
{"1 (default)", "1（默认）"},
{"3-pass mode: 2 real passes + prediction", "3 层模式：2 层真实推理 + 预测"},
{"3-pass mode: 3 real passes", "3 层模式：3 层真实推理"},
{"900/1080 tiers with wave-owned attention and pooled allocations. Applies on network rebuild.\nUses bounded GPU recovery if the queue times out; incompatible layouts use normal launches.", "900/1080 档位使用 wave 分工的注意力计算和内存池，下次重建生效。队列超时时采用有界 GPU 恢复；布局不兼容则使用常规启动方式。"},
{"A buffer the scan found", "扫描找到的缓冲"},
{"A lamp in the corner: red for dark, green for full light, and the\nshades between, with the reading beside it.\n\nIt is how you see at a glance that the scan is TRACKING rather\nthan merely running. Walk into shade and it should slide toward\nred; step out and it should go green. If it moves the wrong way,\nthat is what the setting above is for.\n\nPurely a readout. It changes nothing.", "角落曝光指示器：暗处偏红，亮处偏绿，旁边显示读数。从阴影走到日光下应跟着变化；方向相反时调整相应选项。仅显示读数，不改变画面。"},
{"A multiplier on the exposure the game supplied. 1.00x takes its number\nexactly, and that is the right answer here.\n\nThis is not a fudge factor. If a game needs the trim far from 1 to look\nright, that is evidence the exposure being read is wrong for that game,\nnot that the game wants trimming. Somewhere around 0.8 to 1.25 is honest\ntuning; reaching for 4 means something upstream is broken and the trim is\nhiding it.\n\nYour manual paper white is kept separately and comes back untouched if\nyou switch the option above off.", "游戏曝光的倍率，1.00 使用原值。通常只需在 0.8–1.25 附近微调；若必须调到 4 才正常，更可能是曝光来源错误。手动参考白独立保存，切回手动来源时会恢复。"},
{"A multiplier on the scan's white point, and the control you adjust between\nanchor points: dial it until the picture looks right in the current\nlight, then press Anchor here -- it captures the trimmed value as a new\npoint and resets the trim to 1.", "扫描参考白的倍率。调到当前光照下合适后，点击“在此处设锚点”，保存调整后的值并将倍率恢复为 1。"},
{"ACES (filmic)", "ACES（电影）"},
{"AMD HIP backend. Each pass owns independent temporal history. More passes increase GPU time and memory. Restart the game after a backend failure.", "AMD HIP 后端，每层拥有独立时序历史。增加层数会增加 GPU 时间和显存。后端失败后请重启游戏。"},
{"AUTO", "自动"},
{"Acc. Added Per Frame", "每帧累积量"},
{"Accent Colour", "强调色"},
{"Accept First HUDless", "只接受首份无 HUD 画面"},
{"Active", "运行中"},
{"Active DispatchFlags", "当前 DispatchFlags"},
{"Active Quirks", "当前兼容性规则"},
{"Active input: %s", "当前输入：%s"},
{"Active output: %s", "当前输出：%s"},
{"Active: %s", "当前：%s"},
{"Additional Effects", "附加效果"},
{"Additional colour formats", "额外色彩格式"},
{"Advanced", "高级"},
{"Advanced DA Parameters", "深度感知高级参数"},
{"Advanced FG Settings", "帧生成高级设置"},
{"Advanced Init Flags", "高级初始化标志"},
{"Advanced Kernels", "高级内核设置"},
{"Advanced OptiFG Settings", "OptiFG 高级设置"},
{"Advanced Settings", "高级设置"},
{"Advanced input", "高级输入设置"},
{"Advanced resolution", "高级分辨率设置"},
{"After changing this option, please Save Settings\nIt will be applied on next launch.", "修改后请保存设置，下次启动游戏时生效。"},
{"After changing this option, please Save Settings.\nIt will be applied on next launch.", "修改后请保存设置，下次启动游戏时生效。"},
{"All Ratios", "全局倍率"},
{"Allow Async", "允许异步"},
{"Allow backend hot switching", "允许热切换后端"},
{"Allow backend hot switching (restart)", "允许热切换后端（需重启）"},
{"Allow enhanced barriers", "允许增强屏障"},
{"Allow skin tone / colour changes", "允许肤色色调和色彩变化"},
{"Allow supported additional game colour formats through a private FP16 output.\nRestart the game after changing this setting.", "通过私有 FP16 输出支持额外的游戏色彩格式。修改后需重启游戏。"},
{"Allows WaitForSingleObject instead of spinning for fence value", "使用 WaitForSingleObject 等待 Fence，代替持续自旋。"},
{"Allows XeLL to work without FG on non-Intel cards.\n\nDisables FG options\n\nRequires a restart", "允许非 Intel 显卡在关闭帧生成时使用 XeLL，会禁用帧生成选项。需重启。"},
{"Allows pacing spinlock to sleep, should reduce CPU usage\nMight cause slow ramp up of FPS", "允许帧节奏等待期间休眠，降低 CPU 占用；帧率回升可能变慢。"},
{"Allows the use of a Reactive mask\nKeep in mind that a Reactive mask sent to DLSS\nwill not produce a good image in combination with FSR/XeSS", "允许使用响应遮罩。游戏为 DLSS 提供的遮罩不一定适合 FSR / XeSS，可能影响画质。"},
{"Always Track Heaps", "始终跟踪描述符堆"},
{"Always bucket", "始终按尺寸分组"},
{"Always track resources, might cause performance issues\n, but also might fix HUDFix related crashes!", "始终跟踪资源，可能降低性能，也可能解决 HUD 修复相关崩溃。"},
{"An active limit of 0 means auto-detect the display refresh rate", "实际限制为 0 时，自动读取显示器刷新率。"},
{"Anchor here", "在此处设锚点"},
{"Anisotropic Filtering", "各向异性过滤"},
{"Applies to Daniel, lmxxf and Mochizuki on DX12 and the DX11/Vulkan-to-DX12 bridges.\nNR -> SR enhances the render-resolution input. SR -> NR enhances the upscaled output.\nThe model resolution setting is relative to the selected input; SR -> NR can cost much more GPU time and memory.\nSwitching clears history. If recording hooks were not enabled at startup, Save Settings and restart.\nNative Ray Reconstruction and native Vulkan are not added by this option.\nJittered motion vectors use spatial NR in the experimental path. Unsupported buffers keep the SR image and show a status message.\nINI: [DlssNr] RunBeforeSR=true / false. Save Settings to keep the selection.", "适用于 Daniel、lmxxf、Mochizuki 的 DX12，以及 DX11 / Vulkan 转 DX12 桥接。\nNR -> SR 增强渲染分辨率输入；SR -> NR 增强超分后的输出。模型比例相对于所选阶段的输入，后置 NR 可能大幅增加 GPU 时间和显存占用。\n切换会清空历史；若启动时未准备录制 Hook，请保存后重启。本选项不增加原生光线重建或原生 Vulkan 支持。带抖动的运动矢量使用纯空间 NR；不支持的缓冲保留 SR 图像并显示原因。\nINI：[DlssNr] RunBeforeSR=true / false；保存设置可保留选择。"},
{"Apply", "应用"},
{"Apply Change", "应用更改"},
{"Apply Changes", "应用更改"},
{"Apply Limit", "应用上限"},
{"Apply NR edit", "应用 NR 效果"},
{"Apply Target", "应用目标"},
{"Apply Timing Changes", "应用帧节奏设置"},
{"Apply after Ray Reconstruction (DX12)", "在光线重建后执行 (DX12)"},
{"Apply before Super Resolution", "在超分前执行"},
{"Apply model output", "应用模型结果"},
{"Apply override value as scale multiplier\nWhen using scale mode, please use positive\noverride values to increase sharpness!", "将覆盖值作为倍率使用。此模式下，使用正值增强纹理清晰度。"},
{"Apply same override value to all textures", "对所有纹理使用相同的偏移值。"},
{"Apply the model", "应用模型结果"},
{"Areas that are more red will have more sharpness applied\nGreen areas will get reduced sharpness", "红色越强表示锐化越强，绿色区域降低锐化。"},
{"Auto", "自动"},
{"Auto (existing)", "自动（现有逻辑）"},
{"Auto (inherit pass 1)", "自动（继承第 1 层）"},
{"Auto Exposure", "自动曝光"},
{"Auto bucket", "自动尺寸分组"},
{"Auto exposure", "自动曝光"},
{"Auto skin mask", "自动肤色遮罩"},
{"Automatic character mask", "自动人物遮罩"},
{"Automatic network tier", "自动档位"},
{"Automatic skin mask", "自动肤色遮罩"},
{"Backend", "后端"},
{"Background Alpha", "背景不透明度"},
{"Background Colour", "背景色"},
{"Balanced", "平衡"},
{"Base XeFG multiplier. Kept unchanged while the NR override is active.", "XeFG 基础倍率。NR 覆盖生效期间仍保留此值。"},
{"Base skipped blocks (all passes)", "各层通用跳块"},
{"Base: %lluX | Applied: not initialized", "基础：%lluX | 实际值：尚未初始化"},
{"Base: %lluX | Last applied: %dX", "基础：%lluX | 最近应用：%dX"},
{"Blend GPU: %s", "混合 GPU：%s"},
{"Blends the final NR correction for all backends. 0 = original, 1 = full effect, above 1 amplifies it.\nThis does not reduce model computation. Disable NR to save that work.\nA pure-backend session may require a restart to enable the shared effect recording path.", "混合所有后端的最终 NR 修正：0 为原图，1 为完整效果，大于 1 则增强修正。不会减少模型计算，节省计算需关闭 NR。仅加载单后端的会话可能需要重启，才能准备公共效果录制路径。"},
{"Block rarely used resources from using as HUDless \nto prevent flickers and other issues\n\nHUDfix enable/disable will reset the block list!", "屏蔽很少使用的候选资源，避免将其误作无 HUD 画面造成闪烁。切换 HUD 修复开关会清空屏蔽列表。"},
{"Blue", "蓝色"},
{"Border Size", "边框宽度"},
{"Both", "同时开启"},
{"Bottom Left", "左下"},
{"Bottom Right", "右下"},
{"Bottom left", "左下"},
{"Bottom right", "右下"},
{"Broad structure channel", "广域结构通道"},
{"By default, FSR Anti-Lag 2.0/XeLL is used when available.\nThis setting lets you force LatencyFlex instead", "可用时默认使用 FSR Anti-Lag 2.0 / XeLL，此项强制改用 LatencyFlex。"},
{"CPU timing and sample diagnostics", "CPU 耗时与样本诊断"},
{"Calculate Mipmap Bias", "计算 Mipmap 偏移"},
{"Calculated Cap: %.1f", "建议上限：%.1f"},
{"Camera Far", "相机远裁剪面"},
{"Camera Near", "相机近裁剪面"},
{"Can be toggled with a key -- bind it under Keybinds, \"Neural Rendering\".", "可在“快捷键 → 神经渲染”中绑定开关键。"},
{"Can help with blurry textures in broken games\nNegative values will make textures sharper\nPositive values will make textures more blurry\n\nHas a small performance impact", "可改善部分游戏的模糊纹理。负值更清晰，正值更模糊，对性能有少量影响。"},
{"Can't find nvngx.dll and libxess.dll and FSR inputs\nUpscaling support will NOT work.", "未找到 nvngx.dll、libxess.dll 或 FSR 输入，无法使用超分。"},
{"Cancel", "取消"},
{"Change FG", "切换帧生成"},
{"Change Upscaler", "切换超分"},
{"Cinematic", "电影"},
{"Clamp Output", "限制输出范围"},
{"Clamps the final image to the [0, 1] range.\n\nPrevents overshoot artifacts such as bright halos or negative colors.\nRecommended for LDR pipelines; optional for HDR depending on tone-mapping.\n\nWhen not set OptiScaler controls it via upscalers HDR flag", "将最终画面限制在 [0, 1]，避免亮边和负色值。推荐用于 LDR；HDR 是否需要取决于色调映射。未显式设置时由超分的 HDR 标志决定。"},
{"Classic", "经典"},
{"Clear", "清空"},
{"Click a row to edit it with the slider above; click it again to control the live point. > is the point in use now.", "点击行可用上方滑块编辑，再次点击返回实时值。> 表示当前使用的点。"},
{"Close", "关闭"},
{"Codec paper white", "编解码参考白"},
{"Colour", "色彩"},
{"Colour strength", "色彩强度"},
{"Common", "常用"},
{"Compact 1080 network", "紧凑 1080 网络"},
{"Compare", "画面对比"},
{"Compatibility", "兼容性"},
{"Compatibility & Scheduling", "兼容性与调度"},
{"Contrast", "对比度"},
{"Contrast Enabled", "启用对比度控制"},
{"Controls how strongly sharpening is reduced across depth edges.\n\nHigher values more aggressively prevent sharpening across object boundaries (reduces halos).\nLower values allow more sharpening to pass across edges (sharper but riskier).", "控制跨深度边缘的锐化抑制程度。增大可减少物体轮廓光晕；减小会更锐利，但更容易出现伪影。"},
{"Controls sharpness at high contrast areas.", "控制高对比度区域的锐化。"},
{"Controls the DXGI Present sync interval, which determines how\nthe swap chain waits for vertical refresh.\n\n0  = Present immediately, no VSync wait.\n1  = Sync to every refresh, normal VSync.\n2+ = Present every N refreshes, reducing effective frame rate.\n\nHigher values can reduce tearing but may increase latency and cap FPS.\nFor most games, use 0 for lowest latency or 1 for normal VSync.", "控制 DXGI Present 等待垂直刷新的间隔：\n0：立即呈现，不等待；1：每次刷新呈现；2 及以上：每隔 N 次刷新呈现。\n增大可能减少撕裂，但会增加延迟并限制帧率。通常选择 0（低延迟）或 1（普通垂直同步）。"},
{"Correction hidden; network still runs", "效果已隐藏，网络仍在运行"},
{"Corresponds to amount of accumulation added per frame\nat pixel coordinate where disocclusion occured or when\nreactive mask value is > 0.0f. Decreasing this and \ndrawing the ghosting object (IE no mv) to reactive mask \nwith value close to 1.0f can decrease temporal ghosting.\nDecreasing this could result in more thin feature pixels flickering.", "控制发生遮挡解除或响应遮罩大于 0 的像素每帧增加多少历史累积。降低此值，并在缺少运动矢量的拖影物体上写入接近 1 的响应遮罩，可能减少拖影，但也可能使细线条更闪。"},
{"Cost", "开销"},
{"Current : %.3f / %.3f", "当前：%.3f / %.3f"},
{"Current : %.3f / %.3f, Target: %.3f", "当前：%.3f / %.3f，目标：%.3f"},
{"Current : %.3f / %.3f, Target: Base * %.3f", "当前：%.3f / %.3f，目标：基础值 * %.3f"},
{"Current : %.3f / %.3f, Target: Base + %.3f", "当前：%.3f / %.3f，目标：基础值 + %.3f"},
{"Current DLSSG state:", "当前 DLSSG 状态："},
{"Current FSR-FG state:", "当前 FSR-FG 状态："},
{"Current Preset: %c", "当前预设：%c"},
{"Current Preset: Default", "当前预设：默认"},
{"Current Streamline FG state:", "当前 Streamline 帧生成状态："},
{"Current method: %s", "当前方式：%s"},
{"Cursor Offset X", "光标偏移 X"},
{"Cursor Offset Y", "光标偏移 Y"},
{"Curve", "曲线"},
{"Cutoffs transparency from UI to help with interpolation\nYou can use Show Detected UI to see the difference\n0.0 is auto", "截断 UI 透明度以辅助插帧。可开启“显示检测到的 UI”对照差异，0 为自动。"},
{"DA + MAS Debug", "深度感知 + 运动锐化调试"},
{"DE Ver: %d.%d.%d.%d   GB Ver: %d.%d", "DE 版本：%d.%d.%d.%d   GB 版本：%d.%d"},
{"DEFAULT", "默认"},
{"DLSS NR MFG override", "NR 专用多帧倍率"},
{"DLSS Neural Rendering", "DLSS 神经渲染"},
{"DLSS Settings", "DLSS 设置"},
{"DLSSD Settings", "DLSS RR 设置"},
{"DMFG FPS Target", "动态多帧生成目标帧率"},
{"DRS (Dynamic Resolution Scaling)", "动态分辨率 (DRS)"},
{"Debug", "调试"},
{"Debug Pacing Lines", "显示帧节奏标记线"},
{"Debug Reset Lines", "显示重置标记线"},
{"Debug Tear Lines", "显示撕裂标记线"},
{"Debug View", "调试视图"},
{"Debug view", "调试视图"},
{"Decode GPU: %s", "解码 GPU：%s"},
{"Default", "默认"},
{"Default none. Added to the base skip list only for real network passes 2/3; pass 1 is unchanged.\nThis changes the style and usually saves little time. Not a cheaper equivalent of full multi-pass.\nBlocks 4/69 and byte-stream C64/C128/C256 blocks are unsupported; invalid combinations fall back to no extra skipping.\nPress Enter to apply; rebuilds next frame. Ignored with one pass. A predicted third pass has no extra network blocks.\nINI: DLSS5_MULTI_PASS_SKIP_BLOCKS.", "默认 none，仅给第 2/3 次真实网络推理追加跳块，第 1 层不变。会改变风格，通常只节省少量时间，不等同于低成本完整多层。\n不支持 4/69 和字节流 C64/C128/C256 对应块，无效组合回退为不追加跳块。按 Enter 应用，下一帧重建。单层忽略；预测的第 3 层没有额外网络块。INI：DLSS5_MULTI_PASS_SKIP_BLOCKS。"},
{"Default off. At 2/3 passes, blend skin-coloured regions toward pass 1.\nColour heuristic: may select warm scenery or miss skin under coloured lighting. Ignored with one pass.\nINI: DLSS5_MULTI_PASS_SKIN_PROTECT. Changes rebuild the network next frame.", "默认关闭。2/3 层时将肤色区域向第 1 层结果混合。按颜色识别皮肤，可能把暖色背景也识别进去，或漏掉彩色光照下的皮肤；单层忽略。INI：DLSS5_MULTI_PASS_SKIN_PROTECT。下一帧重建生效。"},
{"Default on in 0.41. Only active with 3 passes: run two real passes and predict the third locally.\nApproximate result; turn off for three real network passes. Passes 1/2 are unchanged by this option.\nINI: DLSS5_MULTI_PASS_PREDICT. Changes rebuild the network next frame.", "0.41 默认开启，仅在 3 层模式生效：两次真实推理后局部预测第 3 层。有近似误差；关闭后执行三次真实推理，不影响 1/2 层。INI：DLSS5_MULTI_PASS_PREDICT。下一帧重建生效。"},
{"Defines the motion range over which the effect ramps from zero to full strength.\n\nValues above the threshold are mapped into this range.\nLarger values make the response smoother and more gradual.\nSmaller values make the effect react more quickly and aggressively.", "超过阈值后，效果从零升至满强度所需的运动范围。范围大则变化平缓，范围小则响应更激进。"},
{"Delay HUDless capture, high values might cause crash!", "延后捕获无 HUD 画面，数值过大可能导致崩溃。"},
{"Denoiser", "降噪器"},
{"Depth Aware (DAS)", "深度感知 (DAS)"},
{"Depth Aware (RCAS)", "深度感知 (RCAS)"},
{"Depth Bias", "深度偏置"},
{"Depth Inverted", "反向深度"},
{"Depth Scale", "深度倍率"},
{"Depth as ValidNow", "深度按 ValidNow 处理"},
{"Depth values will be divided to this value", "深度值除以此数值。"},
{"Detail and colour strength adjust the final correction. Apply model off still runs the network; disable NR to save GPU work.", "细节和色彩强度调整最终修正。关闭“应用模型结果”仍会运行网络，节省 GPU 开销需关闭 NR。"},
{"Detail strength", "细节强度"},
{"Detailed", "详细"},
{"Detailed + Graph", "详细与图表"},
{"Diagnostics", "诊断"},
{"Difference (amplified)", "差异（放大显示）"},
{"Disable DI Tracking", "禁用 DI 跟踪"},
{"Disable DII Tracking", "禁用 DII 跟踪"},
{"Disable Dispatch Tracking", "禁用 Dispatch 跟踪"},
{"Disable HUD/UI interpolation\nReverts back to previous XeFG 2 behaviour\n\nFixes artifacting transparent HUD/UI", "不对 HUD / UI 插值，恢复旧 XeFG 2 行为，可改善半透明界面的画面错误。"},
{"Disable HUDless", "禁用无 HUD 画面"},
{"Disable OM Tracking", "禁用 OM 跟踪"},
{"Disable RTV Tracking", "禁用 RTV 跟踪"},
{"Disable Reactive Mask", "禁用响应遮罩"},
{"Disable SCR Tracking", "禁用 SCR 跟踪"},
{"Disable SGR Tracking", "禁用 SGR 跟踪"},
{"Disable SRV Tracking", "禁用 SRV 跟踪"},
{"Disable UAV Tracking", "禁用 UAV 跟踪"},
{"Disable UI texture", "禁用 UI 纹理"},
{"Disable tracking of CreateRenderTargetView\nThis might help filtering of wrong HUDless resources", "不跟踪 CreateRenderTargetView，可能有助于过滤错误的无 HUD 资源。"},
{"Disable tracking of CreateShaderResourceView\nThis might help filtering of wrong HUDless resources", "不跟踪 CreateShaderResourceView，可能有助于过滤错误的无 HUD 资源。"},
{"Disable tracking of CreateUnorderedAccessView\nThis might help filtering of wrong HUDless resources", "不跟踪 CreateUnorderedAccessView，可能有助于过滤错误的无 HUD 资源。"},
{"Disable tracking of Dispatch\nThis might help filtering of wrong HUDless resources", "不跟踪 Dispatch，可能有助于过滤错误的无 HUD 资源。"},
{"Disable tracking of DrawIndexedInstanced\nThis might help filtering of wrong HUDless resources", "不跟踪 DrawIndexedInstanced，可能有助于过滤错误的无 HUD 资源。"},
{"Disable tracking of DrawInstanced\nThis might help filtering of wrong HUDless resources", "不跟踪 DrawInstanced，可能有助于过滤错误的无 HUD 资源。"},
{"Disable tracking of OMSetRenderTargets\nThis might help filtering of wrong HUDless resources", "不跟踪 OMSetRenderTargets，可能有助于过滤错误的无 HUD 资源。"},
{"Disable tracking of SetComputeRootDescriptorTable\nThis might help filtering of wrong HUDless resources", "不跟踪 SetComputeRootDescriptorTable，可能有助于过滤错误的无 HUD 资源。"},
{"Disable tracking of SetGraphicsRootDescriptorTable\nThis might help filtering of wrong HUDless resources", "不跟踪 SetGraphicsRootDescriptorTable，可能有助于过滤错误的无 HUD 资源。"},
{"Disabled", "已禁用"},
{"Display Res. MV", "输出分辨率运动矢量"},
{"Display Width", "显示宽度"},
{"Display curve the network sees (ToneCurve).\nReinhard usually has better colour; ACES if highlights oversaturate.", "模型所见的显示曲线（ToneCurve）。Reinhard 通常更利于色彩；高光过饱和时可尝试 ACES。"},
{"Display only FSR 3.1 Generated frames", "仅显示 FSR 3.1 生成的帧。"},
{"Display only XeFG generated frames", "仅显示 XeFG 生成的帧。"},
{"Do not use HUDless set at ffxConfig", "不使用 ffxConfig 提供的无 HUD 资源。"},
{"Do not use HUDless set at ffxDispatch", "不使用 ffxDispatch 提供的无 HUD 资源。"},
{"Don't Use NTShared", "不使用 NT 共享句柄"},
{"Don't use reset signals from FG Inputs", "不使用帧生成输入的重置信号。"},
{"Downscaler", "缩小算法"},
{"Downscaler (NR)", "缩小算法 (NR)"},
{"Drain", "排空"},
{"Draw UI over", "叠加 UI"},
{"Draws UI resource over the final image\nIf no UI visible, enable this!", "将 UI 纹理叠加到最终画面；界面消失时可尝试开启。"},
{"Dropped samples: %llu", "丢弃的样本：%llu"},
{"Dump (Shift+Del)", "导出调试数据 (Shift+Del)"},
{"Dx11 with Dx12 Settings", "DX11 转 DX12 设置"},
{"Dynamic resolution", "动态分辨率"},
{"Each internal FSR4 preset is tuned for a specific resolution.\nSelecting an FSR4 preset won't change the in-game\nupscaler preset!!!\n\nPreset 0 is meant for FSR Native AA\nPreset 1 is meant for Quality/Ultra Quality\nPreset 2 is meant for Balanced\nPreset 3 is meant for Performance\nPreset 4 is meant for DRS\nPreset 5 is meant for Ultra Performance", "FSR4 内部预设针对不同分辨率调优，不会改变游戏里的画质档位。\n预设 0：原生抗锯齿；1：质量 / 超高质量；2：平衡；3：性能；4：动态分辨率；5：超高性能。"},
{"Each pass has its own style and model strengths. Changes apply when you release a slider.", "每层独立设置风格和模型强度，松开滑块后应用。"},
{"Each render preset has it strengths and weaknesses\nOverride to potentially improve image quality\nPress Apply after enable/disable", "不同渲染预设各有取舍，覆盖后可能改善画质。启用或关闭后请点击“应用更改”。"},
{"Each render preset has it strengths and weaknesses\nOverride to potentially improve image quality\nPress apply after enable/disable", "不同渲染预设各有取舍，覆盖后可能改善画质。启用或关闭后请点击“应用更改”。"},
{"Early command-list wrap", "提前接管"},
{"Elapsed %.0f s", "已用时 %.0f 秒"},
{"Enable", "启用"},
{"Enable Async for better FG performance\nMight cause crashes, especially with HUD Fix!", "异步可能提高帧生成性能，也可能导致崩溃，尤其与 HUD 修复同用时。"},
{"Enable DA + MAS debug views\nBlue tint for DA detected edges\n\nMore red areas will have more sharpness applied\nGreen areas will get reduced sharpness", "深度感知与运动锐化调试：蓝色表示检测到的深度边缘，红色越强表示锐化越强，绿色区域降低锐化。"},
{"Enable Debug View", "启用调试视图"},
{"Enable Extended Limits", "启用扩展范围"},
{"Enable FSR3.1-FG Debug view\n\nTop left: Game Motion Vectors\nTop middle: GMV Depth\nTop right: Optical Flow MV\nMiddle: Interpolated frame only\nBottom left: Disocclusion mask\nBottom middle: Interpolation source (w/o UI)\nBottom right: HUDless resource", "FSR3.1 帧生成调试视图：\n左上：游戏运动矢量；中上：运动矢量对应深度；右上：光流运动矢量。\n中部：仅插值帧；左下：遮挡解除遮罩；中下：无 UI 的插值来源；右下：无 HUD 资源。"},
{"Enable Frame Generation", "启用帧生成"},
{"Enable HUD stability fix, might cause crashes!", "启用 HUD 稳定性修复，可能导致崩溃。"},
{"Enable Hybrid Spin", "启用混合自旋等待"},
{"Enable Magnifier", "启用放大镜"},
{"Enable Motion Adaptive Sharpness", "启用运动自适应锐化"},
{"Enable NR", "启用 NR"},
{"Enable OptiScaler's sharpening filter\nBy default uses a sharpening value provided by the game\nSelect 'Override' under 'Sharpness' and adjust the slider\nto change it\n\nSome upscalers have their own sharpness filter, so this\noption is not always needed", "启用 OptiScaler 锐化，默认使用游戏提供的强度。要手动调节，请在“锐化”中选择“覆盖”。部分超分算法自带锐化，不一定需要此项。"},
{"Enable RCAS/DA", "启用 RCAS / 深度感知锐化"},
{"Enable Tuning", "启用调节"},
{"Enable WaitForSingleObjectOnFence", "使用事件等待 Fence"},
{"Enable Watermark", "启用水印"},
{"Enable XeFG Debug view", "启用 XeFG 调试视图"},
{"Enable appearance filter", "启用外观过滤器"},
{"Enable effect", "启用效果"},
{"Enable preprocessing", "启用预处理"},
{"Enable the broad structure response in addition to the character channels.", "除人物通道外，同时启用广域结构响应。"},
{"Enable the model's semantic character channels.\nSeparate from Automatic skin mask in the appearance filter.", "使用模型自身的人物识别结果，与外观过滤器按颜色识别皮肤的功能分开控制。"},
{"Enabled", "已启用"},
{"Enables capturing of resources before shader execution.\nIncrease HUDless capture chances, but might cause capturing of unnecessary resources.", "在着色器执行前捕获资源，提高捕获无 HUD 画面的机会，也可能抓到不需要的资源。"},
{"Enables drawing of Interpolation skip lines", "绘制跳过插帧的标记线。"},
{"Enables drawing of Pacing lines", "绘制帧节奏标记线。"},
{"Enables drawing of Tear and Interpolation skip lines", "绘制撕裂及跳过插帧的标记线。"},
{"Enables sharpness adjustments according to the motion", "根据运动幅度调整锐化强度。"},
{"Encode GPU: %s", "编码 GPU：%s"},
{"Encoded", "已编码"},
{"Encoding", "编码"},
{"Enlargement", "放大方式"},
{"Enqueue", "入队"},
{"Error", "错误"},
{"Escape to cancel, Backspace to unbind", "Esc 取消，Backspace 清除绑定。"},
{"Every-frame", "逐帧执行"},
{"Exact", "精确尺寸"},
{"Experimental", "实验功能"},
{"Experimental final-image neural: synthetic motion/depth, no temporal history. Includes game HUD.", "最终画面神经渲染实验：使用合成运动矢量和深度，不使用时序历史，画面包含游戏 HUD。"},
{"Exposure", "曝光"},
{"Exposure bias", "曝光偏置"},
{"Exposure scale", "曝光倍率"},
{"Exposure source", "曝光来源"},
{"Exposure used by the neural model. Auto estimates brightness from the image.\nGame uses the game's exposure texture when available; otherwise it falls back to Auto.\nSeparate from the appearance filter's Exposure (EV).", "模型使用的曝光来源。自动模式从画面估算；游戏模式优先使用游戏曝光纹理，不可用时回退自动。与外观过滤器的曝光 EV 独立。"},
{"Extended", "扩展检查"},
{"Extended FSR FG Settings", "FSR 帧生成扩展设置"},
{"Extended XeFG Settings", "XeFG 扩展设置"},
{"Extended format checks for possible HUDless\nMight cause crashes and slowdowns!", "放宽无 HUD 画面的格式检查，可能引起崩溃或性能下降。"},
{"Extended sliders limit for quality presets\n\nUsing this option changes resolution detection logic\nand might cause issues and crashes!", "放宽画质档位滑块范围，同时改变分辨率检测逻辑，可能导致错误或崩溃。"},
{"External FG is active. Set the multiplier in the game or unlocker, not OptiScaler.", "当前由外部控制帧生成，请在游戏或解锁工具中设置倍率。"},
{"External frame generation / MFG unlocker", "外部帧生成 / 多帧生成解锁工具"},
{"Extra shaders:", "额外着色器："},
{"Extra skipped blocks in passes 2/3", "第 2/3 层追加跳块"},
{"FFX FG", "FFX 帧生成"},
{"FFX Settings", "FFX 设置"},
{"FFX Upscaler", "FFX 超分"},
{"FG Create List", "帧生成创建列表"},
{"FG Input", "帧生成输入"},
{"FG Make Depth Copies", "复制帧生成深度"},
{"FG Make MV Copies", "复制帧生成运动矢量"},
{"FG Nvngx", "Nvngx 帧生成"},
{"FG Nvngx Replacement", "Nvngx 帧生成替代后端"},
{"FG Only Generated", "仅显示生成帧"},
{"FG Output", "帧生成输出"},
{"FG Rectangle Settings", "帧生成区域"},
{"FG Scale Depth Max", "深度缩放除数"},
{"FG Use List", "帧生成使用列表"},
{"FG Use Mutex for Present", "Present 使用互斥锁"},
{"FPS Limit", "帧率上限"},
{"FPS Overlay", "帧率显示"},
{"FPS Overlay Cycle", "切换帧率显示模式"},
{"FPS Overlay Enabled", "显示帧率"},
{"FSR 3 Upscaler Manual Tuning", "FSR 3 超分手动调节"},
{"FSR 3.1 Presets:", "FSR 3.1 预设："},
{"FSR Anti-Lag 2.0 is the new name for AntiLag 2\nDon't ask me why", "FSR Anti-Lag 2.0 是 Anti-Lag 2 的新名称。"},
{"FSR Common Settings", "FSR 通用设置"},
{"FSR Hooks: %s", "FSR 接管：%s"},
{"FSR4 Preset", "FSR4 预设"},
{"FT Input", "帧时间来源"},
{"Fast (cheaper math)", "快速（近似计算）"},
{"Fast numeric approximation", "快速数值近似"},
{"Filmic", "电影"},
{"First use can take longer. NR starts when ready.", "首次准备可能较久，完成后自动启用 NR。"},
{"Fix broken visuals", "修复异常画面"},
{"Fix for DLSS-D wrong depth inputs", "修正 DLSS RR 的错误深度输入。"},
{"Fix for games ignoring official DRS limits", "用于忽略官方 DRS 范围的游戏。"},
{"Fix for games that send motion data with preapplied jitter", "用于已在运动矢量中加入抖动偏移的游戏。"},
{"Fixed", "固定"},
{"Flip (Unity)", "翻转 (Unity)"},
{"Flip Use Offset", "翻转时使用偏移"},
{"Flip Velocity & Depth resources of Unity games", "翻转 Unity 游戏的运动矢量和深度纹理。"},
{"Flip this if the picture gets worse in the direction it should be\ngetting better. Most engines store an exposure that falls as\nthe scene brightens; some store its reciprocal, and a buffer\nfound by shape does not say which. Add a second anchor point in\ndifferent light and this is decided for you, so it disappears.", "若画面变化方向相反，可翻转扫描值。不同引擎可能存曝光或其倒数，单靠缓冲形状无法判断。添加不同光照下的第二个锚点后会自动确定方向，此项随之隐藏。"},
{"Floor of the display curve (ToneLift / Black lift). 0 = none.", "显示曲线的黑位下限（ToneLift / Black lift），0 表示不抬升。"},
{"FoV & Camera Values", "视场角与相机"},
{"For when the game sends HUDless, but you want to disable it", "忽略游戏提供的无 HUD 画面。"},
{"For when the game sends a UI texture, but you want to disable it", "忽略游戏提供的 UI 纹理。"},
{"Force Anisotropic Filtering", "强制各向异性过滤"},
{"Force Borderless", "强制无边框"},
{"Force Dynamic MFG", "强制动态多帧生成"},
{"Force LatencyFlex", "强制 LatencyFlex"},
{"Force Reflex", "强制 Reflex"},
{"Force State", "强制状态"},
{"Force V-Sync On/Off & Sync Interval options", "强制覆盖垂直同步开关和同步间隔。"},
{"Force XeLL", "强制 XeLL"},
{"Forces Borderless display mode\n\nFor best results, set fullscreen \nresolution to your display resolution\nMight cause some instability issues.\n\nNEEDS GAME RESTART TO BE ACTIVE!", "强制无边框显示。建议全屏分辨率与显示器分辨率一致；可能影响稳定性。需重启游戏。"},
{"Frame Ahead", "允许超前帧数"},
{"Frame Generation", "帧生成"},
{"Frame Generation (DLSSG)", "帧生成 (DLSSG)"},
{"Frame Generation (Enabler + FFX)", "帧生成（Enabler + FFX）"},
{"Frame Generation (FSR FG)", "帧生成 (FSR FG)"},
{"Frame Generation (FSR-FG Inputs)", "帧生成（FSR-FG 输入）"},
{"Frame Generation (FSR3-FG via Nukem's DLSSG)", "帧生成（Nukem DLSSG 转 FSR3-FG）"},
{"Frame Generation (FSR3-MFG via DLSS Enabler)", "帧生成（DLSS Enabler 转 FSR3-MFG）"},
{"Frame Generation (FSRFG via FFX)", "帧生成（FFX 转 FSRFG）"},
{"Frame Generation (OptiFG)", "帧生成 (OptiFG)"},
{"Frame Generation (Streamline FG Inputs)", "帧生成（Streamline 输入）"},
{"Frame Generation (XeFG)", "帧生成 (XeFG)"},
{"Frame Pacing Tuning", "帧节奏调节"},
{"Frame generation is off; NR override is inactive.", "帧生成已关闭，NR 倍率覆盖未生效。"},
{"Frame generation rectangle, adjust for letterboxed content", "调整帧生成区域，以适配带黑边的画面。"},
{"FrameTime", "帧时间"},
{"Framerate", "帧率"},
{"Free", "自由位置"},
{"Freezes the frame the model works on. While held, change paper white, the\nstrengths, the reversible mode, the model preset -- anything below the\nupscaler -- and only that setting moves; the scene does not.\n\nWhat it CANNOT show: DLSS/FSR/XeSS upscaler presets or anything upstream\n(the upscaler is not re-run on a held frame), and the game's own HUD and\npost-processing, which run after this pass and keep updating. The white\npoint stops being measured and holds its value while frozen, so it cannot\ndrift and confound the comparison.\n\nHide the menu and it stays held. Untoggle to resume.", "冻结模型处理的画面后，可以调整参考白、强度、代理模式和模型预设，对照同一场景。不会重新运行上游超分，因此不能比较超分预设；游戏后续 HUD 和后处理仍会更新。冻结期间参考白也保持不变。关闭菜单仍保持冻结，取消勾选后恢复。"},
{"Game (auto fallback)", "游戏曝光"},
{"Game input -> %s NR -> Super Resolution", "游戏输入 -> %s NR -> 超分辨率"},
{"Game input -> Super Resolution -> %s NR", "游戏输入 -> 超分辨率 -> %s NR"},
{"Gray", "灰色"},
{"Green", "绿色"},
{"HIP high-priority queue", "HIP 高优先级队列"},
{"HUDFix", "HUD 稳定性修复"},
{"HUDless as ValidNow", "无 HUD 画面按 ValidNow 处理"},
{"High resolution", "高分辨率"},
{"Highlight guard", "高光保护"},
{"History blend", "历史混合比例"},
{"History needs unjittered motion vectors. The separate Residual Stabilizer filters the final correction.", "历史处理需要不含抖动偏移的运动矢量。独立的残差稳定器则平滑最终修正。"},
{"History strength", "历史强度"},
{"Hold frame", "冻结画面"},
{"Horizontal", "横向排列"},
{"Horz. FOV", "水平视场角"},
{"Hot switching requires NrConvenience and command-list hooks armed at startup.\nWith hot switching off, only the selected backend loads.\nClosed GPU recordings retain their resources until Reset/Release and completion.", "热切换要求 NrConvenience 开启，并在启动时准备命令列表 Hook。关闭热切换时仅加载所选后端。已关闭的 GPU 录制会保留资源，直到 Reset / Release 且 GPU 工作完成。"},
{"How far the frame moves toward the model's picture.\n\nThe model's answer is not added to the frame -- it is a complete picture of its\nown, rescaled so its luminance sits where the original says it should. This\nblends between the two, so both ends are real pictures and everything between\nthem is one too.\n\n0 gives back exactly what the upscaler produced. 1 is the model's picture.\nThe lmxxf codec accepts 0 to 3. Above 1 extrapolates past the network result.\n\nThis is the control to push if you want more effect: Intensity belongs to the model\nand it decides what to do with it.", "控制画面向模型结果靠拢的程度：0 为超分原图，1 为完整模型结果。lmxxf 编解码允许 0–3，大于 1 为外推增强。它混合两幅完整画面；模型强度则决定网络本身如何生成效果。"},
{"How long to spin if FPTHybridSpin is true. Measured in timer resolution units.\nNot recommended to go below 2. Will result in frequent overshoots", "混合自旋开启后的自旋时长，单位为计时器分辨率。不建议低于 2，否则容易频繁超时。"},
{"How many frames may be running denoise at once, 2-5. A frame that gets\na buffer waits for its own denoise; one that finds all buffers busy is\nrecorded with NO denoise at all - faster, with possible quality loss.\n\n3 (default): on Onimusha no difference from 2 was detected. In one Where\nWinds Meet A/B session, the skip counter rose by about 1200-1440 per\ntwo-slot segment and stayed flat with 3; that log window does not yield\na skip percentage.\n\n2: in that Where Winds Meet session, display latency was 47.6-47.9 ms\nversus 62.9-63.2 ms with 3, but many frames skipped denoise.\n\n4-5: measured in a separate sweep and no faster than 3 in that scene. A\nscene that actually requires a fourth or fifth slot has not been tested.\n\nEach buffer is one FP16 target at the RENDER size (the DLSS input): about\n29 MB when a 4K output renders at 1440p, 66 MB only at a native 4K render.\nOnly the selected number is allocated. No restart needed.\n\nThe ini also accepts 1 (the old single-slot path); this menu does not.", "同时进行降噪的帧槽位数，范围 2–5。拿到槽位的帧等待自身降噪；槽位全忙的帧不执行降噪，速度更快但可能损失画质。\n默认 3。既往燕云测试中，2 槽出现更多跳过，3 槽计数稳定；该记录不能换算跳过百分比。2 槽显示延迟约 47.6–47.9ms，3 槽约 62.9–63.2ms。另一轮测试中 4–5 槽未比 3 槽更快，不能推断其他场景。\n每槽为渲染尺寸的 FP16 目标：1440p 约 29MB，原生 4K 约 66MB。仅分配所选数量，无需重启。INI 仍接受旧单槽值 1，菜单不提供。"},
{"How much of it lands", "效果应用程度"},
{"How much of the frame each half shows.\n\nA half is half as wide as the frame and just as tall, so the frame\ncannot fill it and keep its shape.\n\nAt 1 the whole frame is there at its right proportions, with bars above\nand below. At 2 the half is filled and the sides are cropped away\ninstead. Anything between trades one for the other.", "控制并排对比每半边显示多少画面。1 保留完整比例但上下有黑边；2 填满半边并裁掉两侧；中间值在保留画面和填满区域之间调整。"},
{"How much of the network's colour replaces the game's hue.\n0: game image as-is (except brightness from Transfer).\n1: network brightness, game colour (safest for saturated scenes).\nAbove 1 blends toward the full network colour (toy; can tint).\nApplies on the next frame. No restart.", "网络色彩对游戏色相的影响：0 保留游戏画面（Transfer 引起的亮度变化除外）；1 使用网络亮度并保留游戏色彩，适合高饱和场景；大于 1 逐渐引入网络色彩，可能产生色偏。下一帧生效。"},
{"How much of the network's detail replaces the upscaler picture.\n0 is the upscaler picture. 1 is the network result.\nAbove 1 pushes past that result, up to 3.\nApplies on the next frame. No restart.", "网络细节对超分画面的替代程度：0 为超分原图，1 为网络结果，大于 1 则外推增强，最高 3。下一帧生效，无需重启。"},
{"How the model's work is brought back up when it ran below the frame's size.\n\nClassic composes the model's small picture directly against the full-size\nframe. Those two disagree by the shrink's blur as well as by the model's edit,\nand the composition cannot tell them apart -- it reads the blur as brightness\nthe frame has and the model never saw. The lower the model resolution the\nlarger that error, and it is the colour shift that shows up at 50%.\n\nMatched residual carries up only the model's difference and lays it on the\nframe's own proxy, so both pictures being compared are full size and the only\nthing that came from the small raster is the edit itself.\n\nNo effect at 100% or above: there is no residual to carry and the two are\nidentical (supersampling brings its answer down to frame size before this).\n\nFrom hhkbble's multi-pass work on this fork.", "模型在较小分辨率运行后如何回到全尺寸。经典模式直接合成小图，可能把缩小造成的模糊误当成模型变化，在 50% 比例时出现色偏。匹配残差仅放大模型带来的差异，再叠加到全尺寸参考画面上。100% 或更高比例时，两种方式的结果相同。源自 hhkbble 的多层实现。"},
{"Hud Cutoff", "HUD 透明度截断"},
{"Hybrid Spin Time", "混合自旋时长"},
{"If UI is too faint, disable this option", "UI 过淡时可尝试关闭。"},
{"If source tags more than one HUDless, only use the first one", "同帧标记多份无 HUD 画面时，只使用第一份。"},
{"If you are using an AMD/Intel GPU, then make sure you have Fakenvapi", "AMD / Intel 显卡请确认已启用 FakeNVAPI。"},
{"If you are using an AMD/Intel GPU, then make sure you have fakenvapi", "AMD / Intel 显卡请确认已启用 FakeNVAPI。"},
{"Ignore Init Checks", "忽略初始化检查"},
{"Ignores all prechecks for XeFG\nDon't use this option to skip MV size warning for UE games!\nIt might cause crashes and bad IQ!", "跳过 XeFG 的初始化预检查。不要用它绕过虚幻引擎游戏的运动矢量尺寸警告，否则可能崩溃或严重影响画质。"},
{"Ignores small depth differences before edge detection.\n\nHigher values reduce flickering and noise from minor depth changes, but may soften real geometry edges.\nLower values preserve fine detail but can cause unstable or noisy edge detection.", "边缘检测前忽略较小的深度差。增大可降低细微深度变化引起的闪烁和噪点，但可能柔化真实边缘；减小保留细节，也更容易不稳定。"},
{"Ignores the value sent by the game\nand uses the value set below", "忽略游戏传入值，使用下方设置。"},
{"Immediate Capture", "立即捕获"},
{"Increasing this scales FSR3.1 computed shading\nchange value at read to have higher reactiveness.", "放大 FSR3.1 计算的着色变化量，使算法更快响应画面变化。"},
{"Increasing this value may reduce white pixel temporal\nflickering around swaying thin objects that are disoccluding \none another often. Too high value may increase ghosting.", "增大可减少细小摆动物体相互遮挡时的白点闪烁，过高则可能增加拖影。"},
{"Information", "信息"},
{"Inherit", "继承"},
{"Init Flags", "初始化标志"},
{"Inline same-frame wait", "同帧等待"},
{"Input", "输入"},
{"Input Color Space", "输入色彩空间"},
{"Input encoding", "输入编码"},
{"Inspect", "检查"},
{"Intensity", "强度"},
{"Interpolated frames only", "仅插值帧"},
{"Jitter Cancellation", "消除抖动偏移"},
{"Just Ext", "仅扩展"},
{"Just FPS", "仅帧率"},
{"Kernel", "内核"},
{"Key combinations are currently NOT supported!", "暂不支持组合键。"},
{"Keybinds", "快捷键"},
{"Label size", "标签大小"},
{"Label the sides", "显示两侧标签"},
{"Language", "语言"},
{"LatencyFlex mode", "LatencyFlex 模式"},
{"Latest", "最新"},
{"Latest supported by the dll", "使用当前 DLL 支持的最新预设"},
{"Leave off unless a game needs NR on lists that use\nenhanced barriers (may corrupt state / TDR). Restart.", "默认关闭。仅当游戏需要在使用增强屏障的列表上执行 NR 时尝试；可能损坏状态或触发驱动超时重置。修改后重启。"},
{"Leaves Streamline, Reflex and FG control to the game/external mod.\nNR and NGX upscaling remain available. Save Settings and restart.\nDoes not install an unlocker or enable FG in unsupported games.", "将 Streamline、Reflex 和帧生成交给游戏或外部模组控制。NR 与 NGX 超分仍可用；保存后重启生效。此选项不会安装解锁工具，也不会为不支持的游戏增加帧生成。"},
{"Lets you override each preset's ratio individually\nNote that not every game supports every quality preset\n\n1.5x on a 1080p screen means internal resolution of 720p\n1080 / 1.5 = 720", "分别覆盖各画质档位的倍率，游戏不一定支持全部档位。例如 1080p 输出设为 1.5 倍，对应内部渲染 720p。"},
{"Light Theme", "浅色主题"},
{"Likely doesn't do much", "此项可能没有明显效果。"},
{"Limit", "限制"},
{"Limits history changes in the compressed colour domain (units of 1/255). Higher values can reduce flicker but increase trailing.", "在压缩色彩域中限制历史变化，单位为 1/255。增大可能减轻闪烁，也会增加拖尾。"},
{"Linear", "线性"},
{"Linear (Default)", "线性（默认）"},
{"List of FGs reported by FFX SDK", "FFX SDK 提供的帧生成后端。"},
{"List of upscalers reported by FFX SDK", "FFX SDK 提供的超分算法。"},
{"Local structure", "局部结构"},
{"Local tone", "局部色调"},
{"Log Level", "日志级别"},
{"Logging", "日志"},
{"Low Latency", "低延迟"},
{"Low latency timings, whole frame: %.1fms", "低延迟统计，整帧：%.1fms"},
{"MAS Debug", "运动锐化调试"},
{"MB Fixed Override", "固定偏移覆盖"},
{"MB Override All Textures", "覆盖所有纹理的偏移"},
{"MB Scale Override", "偏移倍率覆盖"},
{"MFG", "多帧生成"},
{"Magnifier", "放大镜"},
{"Make a copy of depth to use with OptiFG\nFor preventing corruptions that might happen", "为 OptiFG 复制深度，避免资源被覆盖造成画面错误。"},
{"Make a copy of motion vectors to use with OptiFG\nFor preventing corruptions that might happen", "为 OptiFG 复制运动矢量，避免资源被覆盖造成画面错误。"},
{"Make the picture look right, then press this -- it captures the current look\nas a point. For the first point use the Paper white slider above; for\nevery point after, move to different light and use the Trim, which the\nAnchor then bakes into a new point.\n\nThe first press calibrates one point -- the white point then\nfollows the scan by ratio from there, as before. Walk into very\ndifferent light, set paper white again, and press it again: the\nsecond point pins down the buffer's real curve and everything\nbetween the two is right, not just near one anchor. Up to eight.\n\nThe table is per game and shareable: one person calibrates a game\nand the numbers are the same for everyone who takes the profile.", "先将画面调好，再保存当前状态为锚点。第一个点使用参考白；之后换到不同光照，用扫描倍率调节再锚定。一个点按比例跟踪，两个点可确定曲线，最多八个。锚点表按游戏保存，可分享给其他用户。"},
{"Makes a copy of the depth buffer\nCan fix broken visuals in some games on AMD GPUs under Windows\nCan cause stutters, so best to use only when necessary", "复制深度缓冲，可能修复 Windows 下 AMD 显卡在部分游戏中的异常画面，也可能引起卡顿，建议仅在需要时使用。"},
{"Manual paper white when Auto exposure is off\n(including when the game sends pre-exposure).\nHigher darkens the network input and weakens\nhighlight rolloff. Default 8.", "关闭自动曝光时的手动参考白（包括游戏提供预曝光时）。增大会压暗网络输入并减弱高光压缩，默认 8。"},
{"Matched residual", "匹配残差"},
{"Maximum amount of sharpness that motion can add or remove.\n\nNegative values reduce sharpening in motion (recommended).\nPositive values increase sharpening in motion.\n\nThe final adjustment scales with motion and is capped at this value.", "运动可增加或减少的最大锐化量。推荐负值以降低运动中的锐化；正值增强。实际调整随运动变化，并受此值限制。"},
{"Meant for development purpose to test if\nwriting a larger value to reactive mask, reduces ghosting.", "开发调试项：增大响应遮罩值，观察是否减少拖影。"},
{"Menu", "菜单"},
{"Menu Scale", "菜单缩放"},
{"Menu Theme and Color", "菜单主题与配色"},
{"Might be required for some sets of DispatchFlags", "部分 DispatchFlags 组合需要此项。"},
{"Might help achieve better image quality", "可能改善画质。"},
{"Might help achieve better image quality\nAnd potentially less ghosting", "可能改善画质并减少拖影。"},
{"Might help with purple hue in some games", "可能改善部分游戏的紫色色偏。"},
{"Min. Disocclusion Acc.", "遮挡解除最小累积量"},
{"Minimum motion required before motion-based sharpening adjustment begins.\n\nHigher values ignore small movements (more stable).\nLower values react to subtle motion (more sensitive).", "触发运动锐化调整所需的最小运动量。增大可忽略细微运动，更稳定；减小则更灵敏。"},
{"Mipmap Bias", "Mipmap 偏移"},
{"Mochizuki NR - preparing", "Mochizuki NR - 准备中"},
{"Model", "模型"},
{"Model appearance profile. Applies to all active passes.", "模型外观配置，对所有启用层生效。"},
{"Model character mask", "模型人物遮罩"},
{"Model intensity", "模型强度"},
{"Model lighting and colour response. Applied on the first pass.\nSeparate from Tone strength in the appearance filter.", "模型的光照与色彩响应，作用于第 1 层。与外观过滤器的色调强度独立。"},
{"Model output (raw)", "模型原始输出"},
{"Model passes", "模型层数"},
{"Model resolution", "模型分辨率"},
{"Model resolution: ", "模型分辨率："},
{"Model scale", "模型比例"},
{"Modify Compare", "修改比较过滤器"},
{"Modify Min/Max", "修改 Min/Max 过滤器"},
{"Mostly a fix for Unreal Engine games\nTop left part of the screen will be blurry", "主要用于修复虚幻引擎游戏；参数错误可能导致左上区域模糊。"},
{"Motion", "运动"},
{"Motion Adaptive Sharpness", "运动自适应锐化"},
{"MotionRange", "运动范围"},
{"MotionSharpness", "运动锐化强度"},
{"MotionThreshod", "运动阈值"},
{"Multiplier change failed (target %dX). Keeping the last applied multiplier.", "倍率切换失败（目标 %dX），保留最近成功应用的倍率。"},
{"NR -> SR (default)", "NR -> SR（默认）"},
{"NR GPU measures the HIP network. Display uses a 5-sample median after warm-up. Measurement uses non-blocking HIP events and leaves PDL unchanged.", "NR GPU 统计 HIP 网络耗时，预热后显示最近 5 个样本的中位数。测量使用非阻塞 HIP 事件，不改变 PDL。"},
{"NR GPU: %s", "NR GPU：%s"},
{"NR flow", "NR 流程"},
{"NR is off. These nodes describe the configured path.", "NR 已关闭，流程图显示当前配置。"},
{"NR model", "NR 模型"},
{"NR model scale after RR", "RR 后 NR 模型比例"},
{"NR override active: %dX", "NR 倍率覆盖已生效：%dX"},
{"NR override saved; waiting for NR / XeFG to run.", "NR 倍率覆盖已保存，等待 NR / XeFG 开始运行。"},
{"NR override unavailable: this XeSS version cannot change multipliers live.", "当前 XeSS 版本不支持实时切换倍率，无法使用 NR 倍率覆盖。"},
{"NR passes after RR", "RR 后 NR 层数"},
{"NR resolution (%)", "NR 分辨率 (%)"},
{"NR slots", "NR 槽位数"},
{"NVIDIA's internal automatic mask, not the colour-based preview below.\nWith Skin structure=-1 it follows general structure, so the difference may be subtle.\nTry Skin structure=0 versus Local structure=1 to compare. Mask accuracy is model-dependent.", "NVIDIA 模型内部的自动遮罩，与下方基于色彩的预览不同。皮肤结构为 -1 时跟随普通结构，差别可能很小；可用皮肤结构 0、局部结构 1 对照。准确性取决于模型。"},
{"Native Ray Reconstruction has no supported AMD NR seam. This chart describes the Super Resolution path.", "原生光线重建暂没有受支持的 AMD NR 接入点。此图描述超分路径。"},
{"Native input resolution", "原生输入分辨率"},
{"Natural", "自然"},
{"Near: %.1f Far: %.1f", "近：%.1f 远：%.1f"},
{"Needs HUDless texture to compare with final image.\nUI elements and ONLY UI elements should have a pink tint!", "需要无 HUD 纹理与最终画面进行比较。正确检测时，只有 UI 元素应呈粉色。"},
{"Network GPU: %s", "网络 GPU：%s"},
{"Network execution only, not whole NR or frame latency. Detailed timing is in Diagnostics.", "仅统计网络执行耗时，不代表完整 NR 或整帧延迟。详细计时见“诊断”。"},
{"NR active", "NR 运行中"},
{"NR waiting for frame submission", "NR 等待帧提交"},
{"NR waiting for input", "NR 等待输入"},
{"Temporal history unavailable: %s", "时序历史未生效：%s"},
{"Diagnostic view is enabled", "已启用调试视图"},
{"Only one NR pass is supported", "仅支持单层 NR"},
{"The current model layout is unsupported", "不支持当前模型布局"},
{"Motion vector metadata is unavailable", "缺少运动矢量描述信息"},
{"Motion vectors or depth are unavailable", "缺少运动矢量或深度"},
{"Motion vector or depth format is unsupported", "不支持当前运动矢量或深度格式"},
{"Motion vector or depth dimensions do not match", "运动矢量或深度尺寸不匹配"},
{"Motion vector scale or jitter is invalid", "运动矢量缩放或抖动参数无效"},
{"Motion vectors or depth belong to another device", "运动矢量或深度来自其他设备"},
{"The current execution path is unsupported", "不支持当前执行路径"},
{"Network Models", "网络模型"},
{"Network style 0 / 1 / 2. Default: 1.\nChanging style rebuilds the network on the next frame.", "网络风格 0 / 1 / 2，默认 1。修改后下一帧重建网络。"},
{"Network tier", "分辨率档位"},
{"Network tier: ", "分辨率档位："},
{"Neural Rendering", "神经渲染"},
{"Neutral", "中性"},
{"Neutwo proxy + composed", "Neutwo 代理与合成"},
{"No FG", "不使用帧生成"},
{"No active upscaler", "暂无运行中的超分"},
{"No model weights found", "未找到模型权重"},
{"No override", "不覆盖"},
{"No upscaling", "不使用超分"},
{"Non-Linear", "非线性"},
{"Non-Linear sRGB", "非线性 sRGB"},
{"None", "无"},
{"Number of frames the FG is allowed to be ahead of the game\nMight prevent FG on/off switching, but also might cause issues", "允许帧生成领先游戏的帧数。可避免帧生成反复启停，也可能造成其他问题。"},
{"OFF", "关闭"},
{"OK", "确定"},
{"ON", "开启"},
{"Off", "关闭"},
{"Off (default): 1152 processing rows. On: 1088 rows.\nMay reduce NR time but changes the image, especially near the bottom edge.\nOnly affects the 1080 tier; rebuilds on the next frame.", "默认关闭，处理高度为 1152；开启后为 1088。可降低耗时，但会改变画面，尤其是底部边缘。只影响 1080 档位，下一帧重建生效。"},
{"Off (soft knee)", "关闭（柔和拐点）"},
{"Off is the normal picture.\nProxy is what the network is shown. Model output is its raw answer.\nDifference amplifies the edit.\nApplies on the next frame. No restart.", "关闭时显示正常画面。模型输入显示送入网络的画面，模型输出是原始结果，差异视图放大显示修改。下一帧生效，无需重启。"},
{"Off preserves colour in selected pixels; lighting/detail can still change.\nAlso set Skin detail / lighting to 0 to suppress both.", "关闭后保留选中像素的色彩，光照和细节仍可改变。若要同时抑制，请将皮肤细节 / 光照也设为 0。"},
{"Off. The model stays loaded, so turning this back on is immediate.", "已关闭。模型仍驻留，重新开启会立即生效。"},
{"Off: Temporal history on, skip a frame if the previous network is\nstill busy. Closer to 60 FPS; more ghosting because FSR also accumulates.\n\nOn: after Execute, wait for the HIP job only (Temporal off). Does not wait\nfor the D3D12 fence / FSR batch. Closer to danielblnc 0.3's 40+ at a 4K FSR\nUltra Performance render; the next Record may still skip if GPU work is\nin flight.", "关闭：使用时序历史，上一帧网络仍忙时跳过当前帧；帧率通常更高，但与 FSR 历史累积叠加可能增加拖影。\n开启：Execute 后仅等待 HIP 工作，不等待 D3D12 Fence / FSR 批次，不使用此历史模式；GPU 工作未完成时下一次 Record 仍可能跳过。实际帧率取决于游戏和设置。"},
{"On", "开启"},
{"On (default): game waits for NR in the same frame (historical path).\nOff: async (daniel Async=1); pre-upscale is forced off because it requires inline.\nSaved to dlssnr_on_amd.ini only with Save Settings. Restart may be required.", "默认开启：游戏同帧等待 NR，沿用原路径。关闭后改为异步处理（Daniel Async=1）。超分前的 NR 需要同帧等待，因此也会被关闭。点击保存设置才写入 dlssnr_on_amd.ini，可能需要重启。"},
{"On (default): larger Color is fitted onto the 1080 network.\nThat can cost same-frame time and memory.\nOff: a wide frame is admitted only when width is\nat most 2560, height at most 1080, and the pixel count stays\nwithin 1920x1080. 2024x848 passes. 2560x1080 does not.\nApplies on the next frame, including after a resolution change.\nThe network may rebuild once. No restart.", "默认开启：将较大色彩输入适配到 1080 网络，可能增加同帧耗时和显存。关闭后，宽屏输入需同时满足宽 ≤2560、高 ≤1080、像素数 ≤1920×1080；2024×848 可用，2560×1080 不可用。下一帧生效，分辨率改变后可能重建一次，无需重启。"},
{"On (default): lmxxf picks the smallest tier that fits.\nOff: pin NR to one tier in the menu below.\nApplies on the next network rebuild. Written to OptiScaler.ini with Save Settings.", "默认开启：lmxxf 选择能容纳输入的最小档位。关闭后可固定下方档位。下次重建网络时生效，点击保存设置写入 INI。"},
{"On (default): prepare hot switching when lmxxf is installed. Restart after changing.\nOff: start with only the selected backend; changing backends needs a game restart.\nAlso OptiScaler.ini [DlssNr] NrConvenience=0/1.", "默认开启：安装 lmxxf 时预先准备热切换。关闭后仅加载所选后端，切换需重启。修改后重启生效；INI：[DlssNr] NrConvenience=0/1。"},
{"On (default): run at the NR input size, padded for the network.\nNR -> SR uses render resolution; SR -> NR uses the upscaled output resolution.\nHigher resolutions cost more GPU time and VRAM; 4K can be several times slower than 1080p.\nOverrides tier and Compact 1080 settings within the supported processing budget.\nOutside that budget, use the tier settings below. Changes rebuild the network next frame.", "默认开启：按 NR 输入尺寸处理，并补齐网络所需边界。NR -> SR 使用渲染分辨率；SR -> NR 使用超分输出分辨率。\n分辨率越高，GPU 时间和显存占用越高，4K 可能比 1080p 慢数倍。输入尺寸在支持范围内时，忽略分辨率档位和紧凑 1080 设置；超出范围时，改用下方选择的档位。修改后下一帧重建网络。"},
{"On + Ext", "开启并扩展"},
{"On by default. 0.41 extends approximate math from C32/C64/C128 to ViT and C512 projection.\nOutput can differ from 0.40 even with 1/2 passes.\nOff selects the normal numeric modules. Changing this rebuilds the network next frame.", "默认开启。0.41 将近似计算从 C32/C64/C128 扩展到 ViT 和 C512 投影，所以即使 1/2 层也可能与 0.40 不同。关闭使用普通数值模块。下一帧重建生效。"},
{"On: New wait mode (0.3.1 1-pixel draw). Still being tested.\nOff: Original wait mode (switches immediately).\nRestart if prompted: hooks or a pass may not be ready for new wait mode.\nFrames that cannot use new wait mode still fall back to original wait.", "开启：新等待方式（0.3.1 的单像素绘制），仍在测试。关闭：立即切回原等待方式。Hook 或计算层未准备好时按提示重启；不能使用新方式的帧仍回退原方式。"},
{"One pass, 100% image resolution. Restart after resizing the output.", "单层，按画面 100% 分辨率处理。修改输出分辨率后请重启。"},
{"One that only ever climbs is a counter, not an exposure.", "只增不减的值通常是计数器，不是曝光。"},
{"Only Generated", "仅生成帧"},
{"Only turn this off when neural rendering fails to start and the log says missing HIP export hipExtModuleLaunchKernel. Otherwise leave it on.", "仅在 NR 无法启动且日志提示 missing HIP export hipExtModuleLaunchKernel 时关闭，其他情况下保持开启。"},
{"Open release page", "打开发布页面"},
{"OptiScaler - %s for menu", "OptScaler(NR) - 按 %s 打开菜单"},
{"Option disabled because the game doesn't provide a Reactive mask", "游戏没有提供响应遮罩，此选项不可用。"},
{"Optional colour-based selection, NOT NVIDIA's automatic skin mask. Warm scenery can be selected and coloured lighting can hide skin. Check the preview. These controls affect the combined result of all passes.", "可选的色彩筛选，与 NVIDIA 自动肤色遮罩不同。可能误选暖色场景或漏选彩光下的皮肤，请检查预览。控制的是所有层合成后的最终结果。"},
{"Orange", "橙色"},
{"Original wait is active while NR submission hooks are enabled.", "启用 NR 提交 Hook 时使用原等待方式。"},
{"Output", "输出"},
{"Output Scaling", "输出缩放"},
{"Output Scaling is %s, Target Res: %dx%d (%.2f)\nJitter Count: %d", "输出缩放：%s，目标分辨率：%dx%d (%.2f)；抖动采样数：%d"},
{"Output adjustment", "输出调整"},
{"Overall Intensity", "整体强度"},
{"Overlaps HIP kernel launches. Leave this on.\nThe picture is the same either way.\nTurn it off only when neural rendering fails to start\nand the log says: missing HIP export hipExtModuleLaunchKernel.\nThe running chain does not pick this up.", "允许 HIP 内核启动重叠，通常应保持开启，画面结果不变。仅在 NR 无法启动且日志提示 missing HIP export hipExtModuleLaunchKernel 时关闭。已运行的计算链不会即时更新此项。"},
{"Overlay Position", "叠加层位置"},
{"Overlay Type", "叠加层类型"},
{"Override", "覆盖"},
{"Override DLSSG Ratio", "覆盖 DLSSG 倍率"},
{"Override Maximum", "覆盖上限"},
{"Override Minimum", "覆盖下限"},
{"Override XeFG only after DLSS NR successfully runs.\nNever changes the base multiplier or enables frame generation.\nNR off/failure/session rebuild restores the current base multiplier.\nSkipped frames and pauses keep the override. Save Settings to persist.\nChanging multipliers briefly pauses/rearms frame generation.", "仅在 NR 成功运行后覆盖 XeFG 倍率，不改变基础倍率，也不会开启帧生成。NR 关闭、失败或会话重建时恢复当前基础倍率；跳帧和暂停保留覆盖。保存设置可持久化。切换倍率会短暂停止并重新启用帧生成。"},
{"Override all", "覆盖全部档位"},
{"Override all textures mipmap values\nNormally OptiScaler only overrides\nbelow zero mipmap values!", "覆盖所有纹理的 Mipmap 偏移；默认仅覆盖小于零的偏移。"},
{"Override inherited controls", "单独设置"},
{"Override per quality preset", "按画质档位覆盖"},
{"Overrides every upscaler preset with the set value\n\n1.5x on a 1080p screen means an internal res of 720p\n1080 / 1.5 = 720", "用同一倍率覆盖全部超分档位。例如 1080p 输出设为 1.5 倍，对应内部渲染 720p：1080 / 1.5 = 720。"},
{"PDL chained launch", "PDL 链式启动"},
{"Paper white", "参考白"},
{"Paper white only", "仅参考白"},
{"Pass 1", "第 1 层"},
{"Pass 1 preset hint", "第 1 层预设提示"},
{"Pass 2", "第 2 层"},
{"Pass 2 preset hint", "第 2 层预设提示"},
{"Pass 3", "第 3 层"},
{"Pass 3 preset hint", "第 3 层预设提示"},
{"Passes", "层数"},
{"Per shader breakdown:", "各着色器耗时："},
{"Per-pass overrides apply to the DX12 multipass path, including NR after RR. Native Vulkan and the driver-proxy backend remain single-pass.", "逐层覆盖适用于 DX12 多层路径，包括 RR 后 NR。原生 Vulkan 和驱动代理后端仍为单层。"},
{"Performance", "性能"},
{"Please select %s as upscaler from game\noptions and load a save game to enable Opti settings.\nUpscalers don't always work in menus.", "请在游戏选项中选择 %s 超分并载入存档，之后即可调整 OptiScaler。游戏菜单里不一定会运行超分。"},
{"Please select DLSS Frame Generation in the game options\nYou might need to select DLSS first", "请在游戏中选择 DLSS 帧生成，部分游戏需要先选择 DLSS 超分。"},
{"Please select FSR Frame Generation in the game options\nYou might need to select FSR first", "请在游戏中选择 FSR 帧生成，部分游戏需要先选择 FSR 超分。"},
{"Positioning", "位置"},
{"Positive values decrease sharpness at high contrast areas.\nNegative values increase sharpness at high contrast areas.", "正值降低高对比区域的锐化，负值增强该区域锐化。"},
{"Prebuild capacity", "层数预留"},
{"Prebuild passes", "预留层数"},
{"Automatic prebuild capacity grows as needed and is retained on pass reduction. Capacity is not the active pass count.", "自动按需预留更多层的资源；减少执行层数后，仍保留已准备的资源。预留层数不代表实际执行层数。"},
{"Resolution edits apply when editing finishes. 50% halves width and height.", "调整结束后应用分辨率。50% 表示宽和高各减半。"},
{"Pass edits apply when editing finishes. More passes increase GPU cost and memory.", "调整结束后应用层数。层数越多，GPU 耗时和显存占用越高。"},
{"DRS buckets reduce rebuilds when the render size changes. White point controls linear-input brightness.", "尺寸分档可减少动态分辨率变化引起的网络重建。参考白用于调整线性输入的亮度。"},
{"Predict third pass (lossy)", "预测第 3 层（有损）"},
{"Prepare", "准备"},
{"Prepare NR input", "准备 NR 输入"},
{"Preprocessing", "预处理"},
{"Preprocessing changes what the model sees and reverses that transform from its answer.", "预处理先变换模型输入，再对模型输出撤销该变换。"},
{"Preset 0", "预设 0"},
{"Preset 1", "预设 1"},
{"Preset 2", "预设 2"},
{"Preset 3", "预设 3"},
{"Preset 4", "预设 4"},
{"Preset 5", "预设 5"},
{"Presets:", "预设："},
{"Press any key...", "请按任意键…"},
{"Preview colour-based mask", "预览色彩遮罩"},
{"Processing order", "处理顺序"},
{"Protect skin in later passes", "后续层肤色保护"},
{"Proxy (what the model sees)", "模型输入"},
{"Proxy is the picture handed to the model -- if that looks wrong, the white point\nis wrong and nothing downstream can be judged.\n\nDifference shows what the model actually changed, amplified twenty times and\ncentred on grey. A flat grey frame there means it is doing nothing.", "这里显示送入模型的画面，若已不正常，应先检查参考白。差异视图以灰色为中心，将模型修正放大 20 倍；全灰表示没有修正。"},
{"Purple", "紫色"},
{"Puts the edited frame on the other side.\n\nWorth doing once you have decided which you prefer: the eye is not\neven-handed about left and right, and a difference can read as an\nimprovement purely from where it sits. If the same side still wins after\nswapping, it is the pass you are seeing and not the placement.", "交换原图与 NR 结果的位置，便于排除观察时对左右位置的偏好。"},
{"Quality", "质量"},
{"Quality (0.4.2+). Reference keeps NVIDIA's exact arithmetic (default).\nFast is usually visually equivalent and faster.\nRX 7000 always runs Reference.", "画质选项（0.4.2 及以上）。参考模式保留 NVIDIA 精确运算，为默认值；快速模式通常视觉接近且更快。RX 7000 始终使用参考模式。"},
{"QueuePriority=1: high-priority HIP stream (helps under heavy load).\nOff: null stream (QueuePriority=0).\nSaved to dlssnr_on_amd.ini only with Save Settings.", "开启为高优先级 HIP 流（QueuePriority=1），有助于高负载场景；关闭使用默认流（QueuePriority=0）。仅在保存设置时写入 dlssnr_on_amd.ini。"},
{"Ratio", "倍率"},
{"Raw DispatchFlags:", "原始 DispatchFlags："},
{"React. Mask Bias", "响应遮罩偏置"},
{"Reactive Scale", "响应遮罩倍率"},
{"Reading the exposure...", "正在读取曝光…"},
{"Rebuild", "重建"},
{"Rect Height", "区域高度"},
{"Rect Left", "区域左边界"},
{"Rect Top", "区域上边界"},
{"Rect Width", "区域宽度"},
{"Rectangle Settings", "区域设置"},
{"Red", "红色"},
{"Reduces temporal variation in the NR correction using motion and depth.\nMay soften moving detail; disabled by default. Requires valid motion and depth inputs.", "利用运动矢量和深度，减少 NR 修正的逐帧变化。可能柔化运动细节，默认关闭，需要有效的运动和深度输入。"},
{"Reference (NVIDIA-exact)", "参考精度（与 NVIDIA 一致）"},
{"Reflex timings, whole frame: %.1fms", "Reflex 统计，整帧：%.1fms"},
{"Refresh Rate", "刷新率"},
{"Reinhard (soft)", "Reinhard（柔和）"},
{"Relative to RR's OUTPUT resolution: 0.50x at 4K runs NR at 1920x1080.\nRR itself remains full quality. The NR edit is resized for final composition.\nPasses 2 and 3 use the same per-pass model profiles as the SR path.", "相对于 RR 输出分辨率：4K 下 0.50 倍对应 NR 1920×1080。RR 画质不变，NR 修正缩放后合成。第 2/3 层使用与 SR 路径相同的逐层模型参数。"},
{"Relax resolution checks for HUDless by 32 pixels \nHelps games which use black borders for some \nresolutions and screen ratios (e.g. Witcher 3)", "将无 HUD 画面的尺寸检查放宽 32 像素，适用于某些分辨率或宽高比下带黑边的游戏，例如巫师 3。"},
{"Relaxed Resource Check", "放宽资源检查"},
{"Render Presets Override", "覆盖渲染预设"},
{"Render Width", "渲染宽度"},
{"Reprojects the previous model output and uses the model's temporal blend.\nMay reduce brightness flicker, but can add ghosting, soften moving detail and increase GPU cost.\nSupports 1-3 passes before upscaling with valid motion/depth guides.\nPredicted pass 3 uses the last real pass's temporal weight.\nTemporarily disables ViT adaptive reuse to avoid flicker; your reuse settings are retained.\nUnsupported combinations keep your settings and run without history. Default: on.", "重投影上一帧模型输出，交由模型进行时序混合。可能减少亮度闪烁，也可能增加拖影、柔化运动细节并增加 GPU 开销。\n支持超分前 1–3 层，需有效的运动和深度输入。预测第 3 层时使用最后一次真实网络的时序权重。为避免闪烁，开启时暂时禁用 ViT 自适应复用，但保留复用设置。\n不支持的组合保留设置并使用无历史路径，默认开启。"},
{"Requested %lluX exceeds current capability; target limited to %dX. Saved values are unchanged.", "请求 %lluX 超出当前能力，实际目标限制为 %dX，保存值不变。"},
{"Required for Debug flags to work correctly", "调试标志正常工作所需。"},
{"Requires measurement and file logging. At most one summary every five seconds.", "需开启耗时测量和文件日志，每 5 秒最多记录一次摘要。"},
{"Requires the game's native Ray Reconstruction option. RR denoises and upscales\nfirst; NR then processes its output before frame generation.\nThis does not add RR to games without the required rendering buffers.\nIndependent controls below prevent inheriting the cost of the SR configuration.\nNative Vulkan does not use these DX12 controls.", "需要游戏原生光线重建。RR 先降噪和超分，NR 再处理输出，之后才是帧生成。不会为缺少所需缓冲的游戏增加 RR。下方独立参数避免继承 SR 配置开销；原生 Vulkan 不使用这些 DX12 选项。"},
{"Res", "分辨率"},
{"Reset", "重置"},
{"Reset Accent Color", "重置强调色"},
{"Reset BG Colour", "重置背景色"},
{"Reset Camera Values", "重置相机参数"},
{"Reset Depth Values", "重置深度参数"},
{"Reset FG Rect", "重置帧生成区域"},
{"Reset Limit", "重置上限"},
{"Reset List", "重置列表"},
{"Reset NR settings", "重置 NR 设置"},
{"Reset Static Position (Follow Cursor)", "重置位置（跟随光标）"},
{"Reset Target", "重置目标"},
{"Reset backend output", "重置后端输出"},
{"Reset diagnostics", "重置诊断设置"},
{"Reset shared effects", "重置公共效果"},
{"Reset this group", "重置本组"},
{"Reset this page", "重置本页"},
{"Reset to defaults", "恢复默认"},
{"Reset window layout", "重置窗口布局"},
{"Resets Frame generation rectangle", "恢复默认帧生成区域。"},
{"Resets Overall Intensity, residual gains and protections, Person protection, and Residual Stabilizer.", "重置整体强度、残差增益与保护、人物保护参数和残差稳定器。"},
{"Resets mochizuki and shared NR controls. Keeps other backends, selection and hotkeys.", "重置 Mochizuki 和公共 NR 设置，保留其他后端、后端选择和快捷键。"},
{"Resets this backend and shared NR controls. Keeps backend selection, hot-switch preference, keybinds and the other backend settings.", "重置当前后端与公共 NR 参数，保留后端选择、热切换偏好、快捷键和其他后端设置。"},
{"Resets this page's mochizuki controls, including hidden later-pass overrides on the model page. Keeps shared effects and other backends.", "重置本页的 Mochizuki 参数，包括模型页中隐藏的后续层覆盖。保留公共效果和其他后端参数。"},
{"Residual Stabilizer", "残差稳定器"},
{"Residual threshold", "残差阈值"},
{"Resolution", "分辨率"},
{"Resource Barriers", "资源屏障"},
{"Resource Blocking", "资源屏蔽"},
{"Resource Settings", "资源设置"},
{"Restart the game to retry new-wait initialization.", "重启游戏可重新尝试初始化新等待方式。"},
{"Restore Compute Root Signature", "恢复计算根签名"},
{"Restore Graphic Root Signature", "恢复图形根签名"},
{"Retry", "重试"},
{"Reuse global", "全局复用阈值"},
{"Reuse image", "图像复用阈值"},
{"Reuse local", "局部复用阈值"},
{"Reuse period", "复用周期"},
{"Reversible proxy (experimental)", "可逆代理（实验）"},
{"Root Signatures", "根签名"},
{"Runs Neural Rendering on the render-resolution colour input immediately before\nSuper Resolution, so SR temporally accumulates and upscales the enhanced frame.\n\nRay Reconstruction is deliberately excluded: its input contract differs and\nuses the separate Apply after Ray Reconstruction option. Origin-zero padded\ninputs use their active render size; offset or invalid inputs fall back post-SR.\n\nThis placement control currently applies to the Direct3D 12 path and its\nDirect3D 11/Vulkan bridges; native Vulkan keeps the post-upscale path.", "在超分前处理渲染分辨率的色彩输入，再由 SR 累积并放大增强后的画面。光线重建使用独立选项，所需的输入信息不同。原点为零的补齐输入按有效渲染尺寸处理；偏移或无效输入回退后置。适用于 DX12 及其 DX11 / Vulkan 桥接，原生 Vulkan 保留超分后路径。"},
{"Runs sequential model layers between one encode and one final composition.\nEach additional layer consumes the previous layer's model output and owns\na separate persistent feature and temporal history.\n\nThe base proxy stays immutable and the final answer is composed against it\nonce, so colour and transfer strength do not compound. Local tone is applied\nonly by the first layer.\n\nCost scales almost linearly. Two is the common 'deep fried' look; three is\nthe guarded ceiling because later layers converge while cost and artifacts grow.", "在一次编码与最终合成之间串行运行模型层。每层接收上一层输出，拥有独立持久特征和时序历史。最初送入模型的参考画面保持不变，仅最终结果合成一次，因此色彩和修正强度不会逐层叠乘；局部色调仅由第 1 层应用。开销近似随层数增长，后续层的效果趋于收敛，伪影和开销却会上升，因此上限为 3 层。"},
{"SR -> NR (experimental)", "SR -> NR（实验）"},
{"Safety Margins in ms", "安全余量 (ms)"},
{"Safety margins in millisecons\nFSR default value: 0.1ms\nOpti default value: 0.01ms", "安全余量，单位毫秒。FSR 默认 0.1ms，OptiScaler 默认 0.01ms。"},
{"Same as menu", "跟随菜单"},
{"Same-frame", "同帧"},
{"Saturation", "饱和度"},
{"Save Settings", "保存设置"},
{"Save Settings and restart to change frame-generation ownership.", "修改帧生成控制方后，请保存设置并重启游戏。"},
{"Save Settings, then restart the game to use %s.", "保存设置并重启游戏后，将使用 %s。"},
{"Save and restart to change startup hook preparation. Off loads only the active backend.", "修改启动时的 Hook 准备范围，保存后重启生效。关闭时仅加载当前后端。"},
{"Scale", "缩放"},
{"Scale Depth to fix DLSS RR", "缩放深度以修复 DLSS RR"},
{"Scene colour", "环境色彩"},
{"Scene detail / lighting", "环境细节 / 光照"},
{"Select 1-3 passes at the chosen NR/SR stage. With Predict third pass on, 3 uses two real passes plus a local prediction.\nPasses 2/3 add frame-sized buffers. Adaptive ViT reuse is disabled with multiple passes.\nChanging this rebuilds the network next frame; GPU timing includes all passes.", "在所选 NR / SR 阶段执行 1–3 层。开启第 3 层预测时，3 层实际为两次真实推理加局部预测。\n第 2/3 层需要额外的整帧缓冲，多层时禁用 ViT 自适应复用。修改后下一帧重建，GPU 耗时包含全部层。"},
{"Select source for frametime\nMight help frame pacing and stutter issues", "选择帧时间来源，可能改善帧节奏和卡顿。"},
{"Select the input color space that the game uses.\nNon-Linear / sRGB: Might improve FSR4 upscaling quality, might increase ghosting.\nPQ: Rarest, might increase ghosting and break lights.", "选择游戏使用的输入色彩空间。非线性 / sRGB 可能改善 FSR4 画质，也可能增加拖影；PQ 较少见，错误使用可能增加拖影或破坏光照。"},
{"Selected runtime is not installed. Use the package installer.", "所选后端尚未安装，请运行安装包中的安装器。"},
{"Selecting setting below will disable that external override\n", "选择下方设置将取消该外部覆盖。"},
{"Separate skin / environment controls", "分别控制肤色与环境"},
{"Set", "设置"},
{"Set DLSSG interpolation count", "设置 DLSSG 插帧数量。"},
{"Set Static Position", "固定当前位置"},
{"Set as FPS Limit", "设为帧率上限"},
{"Shaders %u / %u", "着色器 %u / %u"},
{"Shading Scale", "着色变化倍率"},
{"Sharpness", "锐化"},
{"Show Debug", "显示调试信息"},
{"Show Detected UI", "显示检测到的 UI"},
{"Show NR performance", "显示 NR 耗时"},
{"Show the light meter on screen", "显示曝光指示器"},
{"Shows the pass against itself, so the two can be seen at once rather than\ntoggled and remembered.\n\nSide by side puts the whole frame in each half, untouched on the left and\nedited on the right. Both halves are squeezed horizontally to fit, so it is\nfor looking at rather than playing in.\n\nWipe cuts a single frame at the split and resamples nothing, so the picture\nis the right shape and can be played normally. Drag the split below; it is a\nstored setting and stays put once the menu is closed.\n\nNeither needs the menu open to keep working. A hairline marks the join.", "同时显示原图和 NR 结果。并排模式将完整画面分别放在两半，适合观察；滑动模式只按分割线显示两种结果，不重采样，适合正常游玩。分割位置会保存，菜单关闭后对比仍继续。"},
{"Side by side", "并排对比"},
{"Simple", "简洁"},
{"Size", "尺寸"},
{"Skin and environment (final edit)", "肤色与环境（最终效果）"},
{"Skin colour", "肤色"},
{"Skin detail / lighting", "皮肤细节 / 光照"},
{"Skin structure", "皮肤结构"},
{"Skin structure -1 follows Structure.", "皮肤结构为 -1 时跟随结构强度。"},
{"Skin structure follows structure", "皮肤结构跟随全局"},
{"Skip Config for HUDless", "忽略 Config 无 HUD 资源"},
{"Skip Dispatch for HUDless", "忽略 Dispatch 无 HUD 资源"},
{"Skip Point Filters", "跳过点采样过滤器"},
{"Skip Reset", "忽略重置信号"},
{"Skip updating of point filters", "不修改点采样过滤器。"},
{"Some NR processing still uses original wait.", "部分 NR 处理仍使用原等待方式。"},
{"Some Unreal Engine games need this\n\nTry using if colours flickering or\nobjects have ghosting trails", "部分虚幻引擎游戏需要自动曝光。遇到色彩闪烁或物体拖影时可以尝试。"},
{"Split", "分割位置"},
{"Stability", "稳定性"},
{"Stabilizer + blend GPU: %s", "稳定器与混合 GPU：%s"},
{"Standard", "标准"},
{"Static Pos X", "固定位置 X"},
{"Static Pos Y", "固定位置 Y"},
{"Static frames reuse ViT; motion returns to full cost.\nTemporarily incompatible with Temporal history due to flicker.\nEnabling adaptive reuse turns off ViT byte stream.\nStrength sliders are tunable (not bit-exact).\nApplies on the next network rebuild.", "静止画面复用 ViT，运动时恢复完整计算。因闪烁问题，暂时与时序历史互斥。开启自适应复用会关闭 ViT 字节流。阈值可调，但结果不是逐位一致。下次网络重建时生效。"},
{"Strength / colour", "强度 / 色彩"},
{"Strength / residual stabilization", "强度 / 残差稳定"},
{"Structure", "结构"},
{"Style", "风格"},
{"Style ", "风格 "},
{"Supersampling %.2fx: the model runs ABOVE native, then\nis sampled back down. Experimental, and costly -- time grows with the area.", "超采样 %.2f 倍：模型在高于原生分辨率运行后再缩小。实验选项，耗时随处理面积增长。"},
{"Swap sides", "交换两侧"},
{"Sync Int.", "同步间隔"},
{"Syncing Settings", "同步设置"},
{"Synthesises detail in the upscaler's frame, before frame generation sees it.\n\nNeeds two similarly named files beside OptiScaler, one character apart:\n  nvngx_dlssnr.dll       NVIDIA's model (~165 MB) -- you supply it\n  nvngx.dll_dlssnr.dll   the forwarder (~13 KB) -- ships in this package\nUndocumented and driven directly, so none of this is officially supported.", "在帧生成之前为超分画面合成细节。OptiScaler 旁需要两个相近文件名：nvngx_dlssnr.dll 为 NVIDIA 模型（约 165MB，需自备）；nvngx.dll_dlssnr.dll 为转发器（约 13KB，包内提供）。此接口未公开，属于实验支持。"},
{"Teal", "青色"},
{"Temporal history", "时序历史"},
{"Temporal history (anti-flicker)", "时序历史（防闪烁）"},
{"The FG that you will actually be using", "实际执行帧生成的后端。"},
{"The data source to be used for FG\nThe native FG which the game supports", "帧生成所用的数据来源，即游戏原生支持的帧生成接口。"},
{"The filter that averages the model's above-native answer back to display size --\nthis is what turns supersampling into LESS noise rather than more. Sharper\nfilters (Lanczos3, Kaiser3) keep the most detail; softer ones (Bicubic,\nCatmull-Rom) are gentler on ringing. Independent of the Output Scaling\ndownscaler, so the two can differ and run at the same time.", "将高于原生分辨率的模型结果缩回显示尺寸的过滤器，有助于降低超采样噪点。Lanczos3 / Kaiser3 保留更多细节；Bicubic / Catmull-Rom 更柔和，振铃较少。与输出缩放的缩小算法独立，可同时使用。"},
{"The game's own exposure", "游戏自身曝光"},
{"The model was trained on finished, sRGB-encoded frames. The upscaler's\noutput is not one: it is linear and open-ended. These decide how it is\nmapped into something the model recognises. A frame the game reports as\nalready tone-mapped is passed over untouched and none of this applies.", "模型以完成色调映射的 sRGB 画面训练，而超分输出可能是未限制范围的线性图像。这些选项负责输入映射；游戏明确报告已完成色调映射时，直接使用原图，不应用此变换。"},
{"The most the pass may move any pixel, as a multiple of what it already was, in\nboth directions -- a pixel may not be brightened past this nor darkened past\nits reciprocal. Lights are where the model has least to say and rescaling its\nanswer does the most damage; 2x leaves detail intact while stopping a strip\nlight turning into a string of coloured cells. Raise it only if bright areas\nlook clipped.", "像素亮度最多改变多少倍，增亮不超过该倍数，变暗不低于其倒数。默认 2 倍通常可保留细节并防止灯带变成彩色块。仅在高光效果受限时提高。"},
{"The number runs the other way", "数值变化方向相反"},
{"The white point for the selected calibration point, or -- with no row\nselected -- the value the next Anchor press captures.\n\nSet it until the picture looks right here, then Anchor. Move to very\ndifferent light and do it again: two points fix the buffer's real\nrelationship and the white point holds between them. Click a row below\nto come back and adjust that point; click it again to let go.", "当前选中锚点的参考白；未选中时用于下一次锚定。先调至当前光照下合适，再设锚点；换到不同光照重复，两个点可确定缓冲的对应关系。点击已有行可重新调整，再点一次取消选择。"},
{"Then: Super Resolution -> game effects / HUD -> presentation", "后续：超分 -> 游戏后处理 / HUD -> 显示"},
{"Then: game effects / HUD -> presentation (game-dependent)", "后续：游戏后处理 / HUD -> 显示（取决于游戏）"},
{"These hints are passed to NVIDIA at creation, but their visual effect is unverified. Use Style for model profile selection. Existing INI hints are preserved.", "创建模型时传给 NVIDIA 的提示参数，视觉效果尚未验证。选择模型风格请使用“风格”，现有 INI 提示值仍保留。"},
{"This setting will become active on next boot!", "下次启动游戏时生效。"},
{"This step has not completed for %.0f s. See mochizuki_nr.log if it persists.", "此步骤已持续 %.0f 秒；若长时间没有进展，请查看 mochizuki_nr.log。"},
{"This usually happens due to using tools\nsuch as Nvidia App or Nvidia Inspector", "通常是 Nvidia App 或 Nvidia Inspector 等工具设置了外部覆盖。"},
{"Tier controls below are the fallback for inputs outside the native-resolution budget.", "输入尺寸超出支持范围时，改用下方选择的分辨率档位。"},
{"To Console", "输出到控制台"},
{"To File", "写入文件"},
{"Tone curve", "色调映射曲线"},
{"Tone intensity", "色调强度"},
{"Tone lift (black)", "黑位抬升"},
{"Tonemap", "色调映射"},
{"Top Left", "左上"},
{"Top Right", "右上"},
{"Top left", "左上"},
{"Top left: Dilated Motion Vectors\nTop middle: Protected Areas\nTop right: Dilated Depth\nMiddle: Upscaled frame\nBottom left: Disocclusion mask\nBottom middle: Reactiveness\nBottom right: Detail Protection Takedown", "左上：膨胀后的运动矢量；中上：保护区域；右上：膨胀后的深度。\n中部：超分输出。左下：遮挡解除遮罩；中下：响应度；右下：细节保护削减。"},
{"Top left: Dilated Motion Vectors\nTop right: Predicted Blend Factor", "左上：膨胀后的运动矢量；右上：预测混合系数。"},
{"Top right", "右上"},
{"Trace", "跟踪"},
{"Tracking Settings", "资源跟踪"},
{"Trim (x the scan)", "扫描值倍率"},
{"UI Composition", "UI 合成"},
{"UI Premult. alpha", "UI 预乘 Alpha"},
{"Ultra Performance", "超高性能"},
{"Ultra Quality", "超高质量"},
{"Uncommon", "不常用"},
{"Unknown", "未知"},
{"Unset controls inherit pass 1, except local tone which defaults to 0. Reset restores this behavior. Only active passes run.", "未设置的参数继承第 1 层，局部色调默认 0。重置恢复此行为，只执行已启用的层。"},
{"Unsupported skip list. Use none or comma-separated block numbers (1-38, 40-68), excluding 4/69. With MH byte stream on, also exclude 5-22 and 48-65. Invalid INI combinations use no extra skipping.", "跳块列表不受支持。请用 none 或逗号分隔编号（1–38,40–68），排除 4/69；开启 MH 字节流时还需排除 5–22 和 48–65。INI 中无效组合回退为不追加跳块。"},
{"Unused", "未使用"},
{"Update comparison filters", "同时修改比较采样过滤器。"},
{"Update min/max filters", "同时修改最小值/最大值采样过滤器。"},
{"Upscale Ratio Override", "覆盖超分倍率"},
{"Upscaler", "超分"},
{"Upscaler Debug View", "超分调试视图"},
{"Upscaler Inputs", "超分输入"},
{"Upscaler Quality", "超分画质"},
{"Upscaler Ratio", "超分倍率"},
{"Upscaler is not active", "超分尚未运行"},
{"Upscalers", "超分辨率"},
{"Upscales the image internally to a higher output resolution\nthen downscales it back to your display resolution\n\nValues <1.0 make the upscaler cheaper\nValues >1.0 make image sharper at the cost of performance\n\nIf greyed out, please check Git Wiki - Unreal Engine tweaks\n\nTarget res and total ratio at the bottom (max. total 3.0!)", "先超分至更高输出分辨率，再缩回显示分辨率。小于 1 可降低开销，大于 1 更清晰但更耗性能。灰显时请参考 Wiki 的虚幻引擎调节说明；下方显示目标分辨率和总倍率（最大 3.0）。"},
{"Upstream default since 0.40: none (all blocks). This base list applies to every real network pass.\nOptional: enter 42,43,46 to skip the three blocks used by the pre-0.40 default. Enter none to run all blocks again.\nThe field below adds skips only in passes 2/3. Skipping changes quality and style.\nPress Enter to apply; rebuilds next frame. INI: DLSS5_SKIP_BLOCKS.\nDisable MH byte stream before skipping blocks 5-22 or 48-65. Blocks 4/69 are unsupported.", "上游从 0.40 起默认 none，即不跳块。本列表作用于所有真实网络层。\n可填 42,43,46，跳过 0.40 之前默认跳过的三个块；填 none 恢复完整执行。下方列表仅给第 2/3 层追加跳块。跳块会改变画质和风格。\n按 Enter 应用，下一帧重建；INI：DLSS5_SKIP_BLOCKS。跳过 5–22 或 48–65 前需关闭 MH 字节流；不支持块 4/69。"},
{"Upstream production kernels. Both (3) is the official 0.35+ template default.\nOff restores the previous f32 ViT path.\nViT stream and ViT byte stream are mutually exclusive.\nEnabling ViT byte stream turns off adaptive reuse.\nApplies on the next network rebuild.", "使用上游正式采用的计算内核。“同时开启”会一起启用 AV FP8 和 Contract F16（配置值 3），这是官方 0.35 起的模板默认设置。关闭后使用原来的 f32 ViT 计算方式。ViT 流式计算与字节流互斥，字节流开启会关闭自适应复用。下次网络重建时生效。"},
{"Use AMD's RCAS\nModified to add Contrast parameter\nand MAS support", "使用 AMD RCAS，增加对比度参数和运动自适应锐化支持。"},
{"Use Binary Reactive Mask", "使用二值响应遮罩"},
{"Use CopyResource for Inputs", "复制输入资源"},
{"Use CopyResource for Output", "复制输出资源"},
{"Use Depth Aware Sharpening (DAS)\nDepth-aware directional adaptive luma sharpener\nSmarter sharpening with less artifacts,\nbut also heavier\n\nThe farther away is the object, the more\nsharpening is applied", "深度感知的方向自适应亮度锐化 (DAS)：物体越远，锐化越强。可能减少伪影，但开销更高。"},
{"Use Depth Aware Sharpening (RCAS)\nSmarter sharpening with less artifacts,\nbut also heavier\n\nThe farther away is the object, the more\nsharpening is applied", "基于深度的 RCAS 锐化：物体越远，锐化越强。可能减少伪影，但开销更高。"},
{"Use FSR Input Values", "使用 FSR 输入值"},
{"Use Ffx Inputs", "使用 FFX 输入"},
{"Use Fsr2 Inputs", "使用 FSR2 输入"},
{"Use Fsr2 Pattern Matching", "使用 FSR2 特征匹配"},
{"Use Fsr3 Inputs", "使用 FSR3 输入"},
{"Use Fsr3 Pattern Matching", "使用 FSR3 特征匹配"},
{"Use Game's Reflex Markers", "使用游戏的 Reflex 标记"},
{"Use Generic App Id with DLSS", "DLSS 使用通用 App ID"},
{"Use Horz. Fov", "使用水平视场角"},
{"Use Precompiled Shaders", "使用预编译着色器"},
{"Use Reactive Mask as Transparency Mask", "将响应遮罩用作透明度遮罩"},
{"Use Theme Colors", "使用主题颜色"},
{"Use Value", "采用此值"},
{"Use Vert. Fov", "使用垂直视场角"},
{"Use generic appid with NGX\nFixes OptiScaler preset override not working with certain games\nRequires a game restart", "NGX 使用通用 App ID，可修复部分游戏中预设覆盖不生效的问题。需重启游戏。"},
{"Use height difference as offset", "以高度差作为偏移量。"},
{"Use mutex to prevent desync of FG and crashes\nDisabling might improve the perf but decrease stability", "用互斥锁防止帧生成失同步和崩溃。关闭可能提高性能，但会降低稳定性。"},
{"Use none or comma-separated block numbers (1-38, 40-68), excluding 4/69. With MH byte stream on, also exclude 5-22 and 48-65.", "填写 none 或逗号分隔的块编号（1–38,40–68），不能包含 4/69。开启 MH 字节流时，也不能包含 5–22 和 48–65。"},
{"V-Sync Off", "关闭垂直同步"},
{"V-Sync On", "开启垂直同步"},
{"V-Sync Settings", "垂直同步"},
{"VRR Frame Cap Calculator", "VRR 帧率上限计算器"},
{"Value of 0.0f can improve temporal stability of bright pixels\nLower values are more stable with ghosting\nHigher values are more pixelly, but less ghosting", "设为 0 可能改善亮点稳定性。较低值更稳定，但拖影更多；较高值拖影较少，但颗粒和跳动更明显。"},
{"Values above 0 activate usage of Reactive mask", "大于 0 时启用响应遮罩。"},
{"Variance Factor", "方差系数"},
{"Variance factor\nFSR default value: 0.1\nOpti default value: 0.3", "方差系数。FSR 默认 0.1，OptiScaler 默认 0.3。"},
{"Velocity Factor", "速度系数"},
{"Velocity as ValidNow", "运动矢量按 ValidNow 处理"},
{"Vert. FOV", "垂直视场角"},
{"ViT / image reuse", "ViT / 图像复用"},
{"ViT adaptive reuse", "ViT 自适应复用"},
{"ViT adaptive reuse is unavailable while Temporal history is enabled. Your settings are retained.", "时序历史开启时，ViT 自适应复用暂不可用。原有设置已保留。"},
{"ViT byte stream (exp)", "ViT 字节流（实验）"},
{"ViT stream (exp)", "ViT 流式计算（实验）"},
{"Vulkan network timing uses completed timestamp queries. Median and p95 cover up to 120 samples; copies and whole-frame latency are separate.", "Vulkan 网络耗时取自已完成的时间戳查询。中位数和 p95 最多统计 120 个样本，不包含完整拷贝或整帧延迟。"},
{"Vulkan with Dx12 Settings", "Vulkan 转 DX12 设置"},
{"Waiting for a frame...", "等待画面…"},
{"Waiting for the upscaler to run.", "等待超分开始运行。"},
{"Walk from shade into daylight. A real exposure moves.", "从阴影走到日光下，真正的曝光值应随之变化。"},
{"Warning", "警告"},
{"Watermark", "水印"},
{"What backend to use instead of the real DLSSG", "用于替代原生 DLSSG 的后端。"},
{"What fraction of the frame the model works at. Cost falls with the square of\nthis, so half resolution is roughly a quarter of the time.\n\nThe frame is never reduced. Only the model's contribution is computed small\nand enlarged, so the picture underneath is untouched whatever this says.\n\nWhat it trades: the shading the model adds is broad and survives enlargement;\nthe fine structure it synthesises does not, and softens. Worth having when the\npass costs more than you want to pay for the detail it returns.\n\nThe frame itself stays at full detail whatever this says -- only the\nmodel's own work is done small.", "模型处理分辨率的比例，面积近似随比例平方变化，半分辨率约为四分之一计算量。原画面始终保留完整细节，仅模型修正在较小尺寸计算后放大；大范围光照变化较易保留，模型合成的精细结构会变软。"},
{"What the frame is divided by before the model sees it. There is no other white\npoint; this is the whole of it.\n\nThe model was trained on finished frames where white sits at 1. The\nupscaler's output is linear and open-ended, so something has to say where\nwhite is -- and where the game's DLSS buffer is linear HDR, that number is\nrarely anywhere near 1. Measured in Monster Hunter Wilds it takes 16 or more\nbefore the model's detail reaches the frame at all, and the value that suits\na shaded camp is still too small for the same game out in daylight.\n\nToo low and almost every pixel trips the soft knee: the model is shown a\nflat near-white picture, its answer is scaled away, and only its hue\nsurvives -- which reads as a colour cast rather than as lost detail. Too\nhigh and it is shown an underexposed one, its answer degrades, and this same\nnumber multiplies that error on the way out.\n\nRaise it until the picture stops improving. Past that point it does not\nplateau, it gets worse in the other direction.\n\nThis was once a multiplier on a measured white point. The measurement is\ngone: it read scene brightness rather than where white belongs, handed the\nmodel a picture three times too dark, and left the highlight path nothing to\ngive back.\n\nAt strength zero the frame is still bit-identical whatever this says.", "模型输入前的亮度除数。线性 HDR 画面的参考白通常不为 1，并随游戏和场景光照而异。过低会把输入压成近白画面，丢失细节并留下色偏；过高会使输入欠曝并放大输出误差。逐步调至画面最佳，继续增大可能反而变差。此值现为完整参考白，不再乘以旧亮度测量值；效果强度为零时仍返回原图。"},
{"What the model is shown, and how its answer comes back.\n\nOff (soft knee): the default. It rolls highlights off so hard the model\ncannot resolve detail in them -- fine in soft-lit scenes, weak in bright ones.\n\nNeutwo composed: an unclipped curve so the model sees highlight detail, then\neverything above (Detail/Colour strength, highlight guard, palette). It wins in\nbright scenes, but the curve compresses MIDTONES too, so in soft-lit content it\ncan be worse than Off. It also shifts paper white -- re-check it when you switch.\n\nHybrid composed: the best of both, and the one to use. Identity in the\nmidtones -- as good as Off there -- and the unclipped roll only in the\nhighlights, so it recovers the detail Off crushes without giving up the\nmidtones Neutwo does. It barely shifts paper white.\n\nReplace: the raw model straight back through the exact inverse, none of the\ncomposition -- no guard, no palette, no strengths. Gorgeous where there are no\nbright lights, but they FLASH in motion. A reference, not a daily setting.\n\nHybrid replace: the raw model like Replace, but on the hybrid curve -- the\ndecode is identity in the midtones, so the flashing is confined to genuine\nbright highlights instead of everywhere. Most of Replace's detail, far more\nstable. If you love the Replace look but the flicker bothers you, use this.\n\nOff is byte-identical to before.", "控制模型输入代理与输出还原。\n关闭（柔和拐点）：默认，高光压缩较强，柔和光照下较稳。Neutwo 合成：保留更多高光细节，但也压缩中间调，切换后需检查参考白。Hybrid 合成：中间调保持原样，只压缩高光，通常更均衡。\nReplace：直接逆变换原始模型输出，不使用强度、高光保护和色彩合成；亮部运动时可能闪烁，适合对照研究。Hybrid Replace：使用混合曲线，只在真实高光区域更易闪。\n关闭保持原有逐字节结果。"},
{"Whatever the game uses", "跟随游戏设置"},
{"When the game does not send a usable exposure texture,\nmeasure the frame's mean brightness once per frame and\nsmooth it over time so highlights do not jump.\nIgnores Exposure scale.\nGames that already pass exposure are unchanged.\nApplies on the next frame. No restart.", "游戏未提供可用曝光纹理时，每帧测量平均亮度并进行时序平滑，减少高光跳变。忽略曝光倍率；游戏已有有效曝光时保持原行为。下一帧生效，无需重启。"},
{"Where the number that divides the frame comes from.\n\nPaper white only -- the slider below and nothing else. Right for a\ngame whose exposure never moves, wrong the moment it does: one\nconstant cannot serve a cave and a field.\n\nThe game's own exposure -- read from the texture the game hands\nthe upscaler. The best source there is, because it is decided\nupstream and nothing this pass does can move it. Not every game\nsupplies one.\n\nA buffer the scan found -- for games that compute an exposure and\nnever pass it on. A GUESS: candidates are matched by shape, and in\nGTA V the best one tracks the real exposure but at its own scale,\nwhich the anchor's ratio cancels. Needs anchoring once, and checking\nafterwards.", "输入亮度除数的来源。仅参考白使用手动固定值，无法跟随变化的曝光。游戏自身曝光直接读取游戏交给超分的纹理，是优先选择，但部分游戏不提供。扫描缓冲仅按形状猜测候选，数值可能有不同倍率，需要设置锚点并验证。"},
{"Where the wipe cuts. Left of it is the frame as the upscaler produced it,\nright of it is the frame the model edited.", "滑动对比的分割位置：左侧为超分原图，右侧为模型修改后的画面。"},
{"Whether the model's colour arrives with its light.\n\n0 keeps the game's own hue exactly -- every pixel is the original colour with\nonly its brightness carrying the model's verdict. Game-accurate colour, with\nthe detail. 1 brings the model's colour as well, in its own hue, clamped into\nAP1 so nothing unreachable is asked for.\n\nThis cannot shift hue on its own: it interpolates between two finished\npictures rather than adding a colour difference to one, which is what used to\nlet a warm subject come back green.\n\nAbove 1 it OVER-SATURATES: the colour keeps its hue but grows more vivid,\nand rolls off at the edge of what the display can show rather than clipping\ninto a flat blown patch. 1 is the model's own colour; push past it for punch.\nThe lmxxf codec accepts 0 to 3.", "控制是否引入模型色彩。0 保留游戏色相，仅改变亮度；1 引入模型色彩并限制在 AP1 范围内。两幅完整画面之间插值，不直接叠加色差。大于 1 增强饱和度并在显示边界渐变压缩；lmxxf 编解码允许 0–3。"},
{"Whether the model's edit is applied. Off shows the clean upscaler frame while the\npass keeps running -- so with Hold frame (under Compare) you can freeze a\nframe and toggle this to see the same frozen frame with and without Neural\nRendering. Leave it on for normal use.", "控制是否应用模型修正。关闭显示超分原图，但网络继续运行；配合冻结画面，可对照同一帧开关 NR 的差异。日常使用保持开启。"},
{"Which copium do you choose?", "选择使用的超分算法。"},
{"White level used by encode and decode. Default 1.\nLog slider, so 1 is easy to land on. Reset returns to 1.\nNot the HDR Paper White control further down.\nApplies on the next frame. No restart.", "编解码使用的白电平，默认 1。滑块使用对数刻度，便于定位 1；重置恢复 1。与下方 HDR 参考白不同。下一帧生效，无需重启。"},
{"White point", "参考白"},
{"White point from", "参考白来源"},
{"Wiki", "使用指南"},
{"Will be applied after RESOLUTION/PRESET change !!!", "更改分辨率或画质档位后生效。"},
{"Will might be applied after RESOLUTION/PRESET change !!!", "可能需要更改分辨率或画质档位后才生效。"},
{"Will use more VRAM, but Uniscaler needs this\nMaybe some other games might need too", "会增加显存占用；Uniscaler 和部分游戏需要此选项。"},
{"Will use more VRAM, but some games might need this", "会增加显存占用，但部分游戏需要此选项。"},
{"Window", "窗口位置"},
{"Wipe", "滑动对比"},
{"Without override, later passes inherit pass 1 with Local tone set to zero.", "未开启“单独设置”时，后续层沿用第 1 层参数，局部色调强度固定为 0。"},
{"Wrap command lists created before the swapchain. Shared by lmxxf and Mochizuki.\nAuto: EXE calls in Unreal/Forza; UnityPlayer.dll calls in Aniimo only.\nForce on: EXE calls and UnityPlayer.dll calls in other Unity games too.\nForce off: disable both early paths; normal post-swapchain wrapping stays enabled.\nOther games are unvalidated; forcing early wrap can cause startup problems.\nSave and restart to apply. INI: LmxxfEarlyExeWrap.", "接管交换链创建前生成的命令列表，lmxxf 与 Mochizuki 共用。\n自动：虚幻 / Forza 的 EXE 调用，以及伊莫的 UnityPlayer.dll 调用。强制开启：还覆盖其他 Unity 游戏的 UnityPlayer.dll 调用。强制关闭：禁用上述提前接管，保留交换链创建后的正常接管。\n其他游戏未经验证，强制开启可能导致启动问题。保存后重启生效；INI：LmxxfEarlyExeWrap。"},
{"Write timing summary to log", "将耗时摘要写入日志"},
{"Writes which side is which onto the frame itself, so a screenshot still\nsays so after it has left this machine. Drawn into the picture's own\nplane: in the wipe the split reveals and hides the label exactly as it\ndoes the images, and there is nothing to drag. Swap sides moves the\nlabels with their pictures.", "将两侧说明绘制到画面中，截图也能保留。滑动对比时标签与画面一起被分割线裁切，交换两侧时标签跟随画面。"},
{"XeSS Settings", "XeSS 设置"},
{"XeSS disabled FG after a multiplier error. Restart the game to reinitialize XeSS.", "XeSS 因倍率错误关闭了帧生成，请重启游戏重新初始化。"},
{"Yellow", "黄色"},
{"You shouldn't need to change it", "通常无需修改。"},
{"Zero", "零"},
{"Zoom", "缩放"},
{"Zoom Factor", "放大倍率"},
{"auto (Unreal/Forza/Aniimo)", "自动（虚幻 / Forza / 伊莫）"},
{"daniel extras live in dlssnr_on_amd.ini [DlssNrOnAmd]: PollSpacing, OverlayKey, HipDevice, InlineWaitMs, ...\nIns menu / OptiScaler.ini win on Save for keys this menu exposes.\nOverlayKey only binds daniel's own overlay (unused when driving from Ins).\nProcess env (advanced, no Ins toggle): DLSSNR_NO_REG, DLSSNR_CHAIN, DLSSNR_NOBLEND, DLSSNR_NO_REPACK, DLSSNR_WBLOG.", "Daniel 额外选项位于 dlssnr_on_amd.ini 的 [DlssNrOnAmd]：PollSpacing、OverlayKey、HipDevice、InlineWaitMs 等。菜单已提供的键在保存时以 Ins / OptiScaler.ini 为准。OverlayKey 仅绑定 Daniel 自带叠加层。高级环境变量（无菜单开关）：DLSSNR_NO_REG、DLSSNR_CHAIN、DLSSNR_NOBLEND、DLSSNR_NO_REPACK、DLSSNR_WBLOG。"},
{"force off", "强制关闭"},
{"force on", "强制开启"},
{"frames", "帧"},
{"lmxxf HIP backend. Same-frame execution at the selected processing stage.", "lmxxf HIP 后端，在所选处理阶段同帧执行。"},
{"lmxxf style", "lmxxf 风格"},
{"nvngx replacement: %s", "nvngx 替代实现：%s"},
{"nvngx.ini detected: use OptiScaler.ini and remove the old config.", "检测到 nvngx.ini，请改用 OptiScaler.ini 并移除旧配置。"},
{"| Input: %s", "| 输入：%s"},
{"| Spoof: %s", "| 伪装：%s"},
{"Vulkan core GPU: %.3f ms | Network: %.3f ms | Other: %.3f ms", "Vulkan 核心：%.3f ms | 网络：%.3f ms | 其他：%.3f ms"},
{"Completed-sample means. Network includes fused temporal shaders; Other covers core input, history copies and composition. Bridge copies, shared effects and whole-frame latency are excluded.", "显示已完成样本的平均耗时。网络包含融合的时序着色器；其他包含核心输入处理、历史拷贝和合成。不含桥接拷贝、公共效果及整帧延迟。"},
{"Mochizuki Vulkan core total, including its input and composition. Excludes bridge copies and shared effects. Timing breakdown is in Diagnostics.", "Mochizuki Vulkan 核心总耗时，包含其输入处理与合成，不含桥接拷贝和公共效果。耗时拆分见诊断。"},

{"Model enlargement", "模型放大"},
{"Edge-aware", "边缘引导"},
{"Reuse output buffer", "复用输出缓冲"},
{"Model enlargement applies below 100% model scale. Matched residual is the default; edge-aware costs more GPU time.\nReuse output buffer saves one full-resolution float image on supported formats. Switching rebuilds the network; turn off to use separate buffers.", "模型分辨率低于 100% 时生效。默认使用匹配残差；边缘引导更耗时。\n支持的格式可复用输出缓冲，省去一张全分辨率浮点纹理。切换会重建网络；关闭可退回独立缓冲。"},
{"Rendering", "渲染"},
{"Upscaling", "超分辨率"},
{"Latency & FPS", "延迟与帧率"},
{"System", "系统"},
{"Textures", "纹理"},
{"Help / Status", "帮助与状态"},
{"Backend, processing order, passes and NR output.", "选择后端、处理顺序、层数与 NR 输出。"},
{"Upscaler, sharpness and output resolution.", "调整超分算法、锐化与输出分辨率。"},
{"Frame generation source, output and pacing.", "设置插帧输入、输出与帧节奏。"},
{"Frame limiter, low latency and V-Sync.", "设置帧率上限、低延迟与垂直同步。"},
{"Mipmap bias, filtering and magnifier.", "调整纹理细节、过滤与放大镜。"},
{"Input flags, resource barriers and game workarounds.", "调整输入标志、资源屏障与游戏兼容选项。"},
{"Theme, scale, overlay and keybinds.", "设置主题、缩放、性能浮窗与快捷键。"},
{"Detected components, active inputs and logging.", "查看已检测组件、当前输入与日志设置。"},
{"GPU: %s", "显卡：%s"},
{"API: %s", "图形接口：%s"},
{"Upscaler: %s", "超分算法：%s"},
{"Background blur", "背景模糊"},
{"Blur strength", "模糊强度"},
{"Reset blur", "重置模糊"},
{"Blurs the game behind this menu. Requires a translucent background.\nUnsupported swapchain formats keep the normal menu background.", "模糊菜单背后的游戏画面，需使用半透明背景。\n不支持的交换链格式会保留普通菜单背景。"},
{"Low-frequency gain", "低频增益"},
{"Adjusts broad changes in NR lighting and colour. 1 = unchanged. Shared by all backends, after their history.\nNo additional network pass; spatial processing still has a GPU cost.", "调节 NR 对大块明暗和色调的改变，1 为原强度。三后端共用，在各后端历史处理之后生效。\n不增加网络层数，但空间处理仍有 GPU 开销。"},
{"Fine-detail gain", "细节增益"},
{"Adjusts fine-scale NR changes without blurring original detail. Below 1 reduces fine residual noise; above 1 can increase flicker.\nThis strengthens an existing pass, not a real second pass.", "调节 NR 新增的细碎变化，不模糊原图细节。低于 1 可减弱细碎残差噪声，高于 1 可能加重闪烁。\n这是已有层的效果增益，不等于再跑一层网络。"},
{"Skin detail protection", "肤色细节保护"},
{"Experimental: limits new fine-scale NR changes in skin-like colours, guided by original detail. 0 = off.\nA colour heuristic, not person detection: warm backgrounds can also be affected. HDR appearance needs testing.", "实验性：参考原图细节，限制肤色区域新增的细碎变化。0 为关闭。\n只按颜色判断，不是人物识别，暖色背景也可能受影响。HDR 观感仍需实测。"},
{"Edge detail protection", "边缘细节保护"},
{"Experimental: limits new fine-scale NR changes near strong original edges. 0 = off. Keeps original edges and alpha.\nCan weaken intended NR detail; this is spatial protection, not temporal anti-flicker.", "实验性：限制原图强边缘附近新增的细碎变化。0 为关闭，保留原图边缘和透明度。\n也可能减弱需要的 NR 细节；这是空间保护，不是时序抗闪烁。"},

{"Person first pass", "人物保留首层"},

{"Experimental: person uses the first NR pass; scene uses the final pass. Requires person-model/onnxruntime.dll and yolo11n-seg.onnx (COCO FP32 640).\nCPU inference is asynchronous. Missing, stale or misaligned masks preserve final NR. Does not reduce network passes.", "实验功能：人物使用第一层 NR，场景使用最后一层。需自行准备 person-model/onnxruntime.dll 和 yolo11n-seg.onnx（COCO FP32 640）。\n人物识别在 CPU 后台运行。蒙版缺失、过期或无法对齐时保留最终 NR；不会减少网络计算层数。"},

{"Available with lmxxf and Mochizuki multi-pass.", "仅支持 lmxxf 和 Mochizuki 多层。"},
{"off", "关闭"},
{"loading person model", "正在加载人物模型"},
{"person mask ready", "人物蒙版已就绪"},
{"person model ready", "人物模型已就绪"},
{"Person: first pass / scene: final pass", "人物使用首层，场景使用末层"},
{"Person partition: waiting for a current mask", "人物分区：等待当前蒙版"},
{"Person partition bypassed: first pass or reliable motion/depth unavailable", "人物分区未生效：缺少首层输出或有效的运动与深度数据"},
{"missing person-model/onnxruntime.dll (ONNX Runtime 1.23+ CPU x64)", "缺少 person-model/onnxruntime.dll（ONNX Runtime 1.23+，CPU x64）"},
{"missing person-model/yolo11n-seg.onnx (FP32 640, COCO)", "缺少 person-model/yolo11n-seg.onnx（FP32 640，COCO）"},
{"missing person-model/person-worker.exe; install the complete package", "缺少 person-model/person-worker.exe，请完整更新安装包"},
{"person worker protocol mismatch; install the complete package", "人物识别程序版本不匹配，请完整更新安装包"},
{"person worker timed out; toggle person protection to retry", "人物识别超时，请关闭再开启人物保护以重试"},
{"person worker returned a mismatched frame", "人物识别返回了不匹配的画面，已停用"},
{"cannot load ONNX Runtime CPU x64", "无法加载 ONNX Runtime CPU x64"},
{"ONNX Runtime C API 23 unavailable", "ONNX Runtime 不支持 C API 23"},
{"requires YOLO11n-seg FP32 640 export", "需要 YOLO11n-seg FP32 640 模型"},
{"unsupported person model dimensions", "人物模型尺寸不受支持"},
{"person recording memory budget busy", "人物分区显存预算暂时不足"},
{"person inference failed", "人物识别失败"},
{"person preparation failed", "人物分区准备失败"},

{"Person protection", "人物保护"},
{"Person NR strength", "人物强度"},
{"Person detail", "人物细节"},
{"Person protection active", "人物保护已生效"},
{"Available with lmxxf and Mochizuki.", "支持 lmxxf 和 Mochizuki。"},
{"Single pass: lower person strength or detail to apply protection.", "单层时，降低人物强度或人物细节才会改变画面。"},
{"Experimental: single pass uses final NR; multi-pass keeps pass 1 for people. Scene uses final NR. Requires the person model and ONNX Runtime.\nThis does not change backend character/skin controls or reduce network passes. Missing or invalid masks preserve final NR.", "实验功能：单层使用当前 NR 结果，多层时人物保留第一层，场景使用最终层。需要人物模型和 ONNX Runtime。\n不会修改后端的角色/肤色参数，也不会减少网络计算。蒙版缺失或失效时保留正常 NR。"},
{"1 keeps the selected NR pass. 0 keeps the NR input inside a reliable person mask, before shared output effects.\nBackend character controls and Overall Intensity still apply; combining protections can weaken the result.", "1 保留选定层的 NR 效果；0 在可靠的人物区域保留 NR 输入画面，之后仍会经过公共输出调节。\n后端角色控制和整体强度仍然有效，叠加多项保护可能让人物效果过弱。"},
{"Reduces fine NR changes on people while retaining broad lighting changes and original detail. 1 = unchanged.\nThis uses the full person mask, not precise face or skin detection. Shared residual gains still apply afterwards.", "减少 NR 在人物上新增的细碎纹理，保留大范围明暗变化和原图细节。1 不作调整。\n作用于完整人物蒙版，不是精确的人脸或皮肤检测；之后仍会经过公共残差增益调节。"},
{"Show person mask overlay", "显示人物蒙版诊断"},
{"Displays a green overlay on detected person areas for alignment and stability diagnostics.", "在识别到的人物区域显示绿色半透明蒙版，用于诊断检测范围、边缘贴合度与时序稳定性。"},
{"Person model", "人物识别模型"},
{"PP-HumanSeg (Fast ~8ms)", "PP-HumanSeg（极速 ~8ms）"},
{"YOLO11n-seg (Baseline ~64ms)", "YOLO11n-seg（基准 ~64ms）"},
{"YuNet (Face only)", "YuNet（仅面部）"},
{"Only the selected model runs. PP-HumanSeg and YOLO cover the body; YuNet protects detected faces with a soft oval.\nYuNet offers 320, 384 and 416 inputs. Small, turned or occluded faces may be missed; hair and clothing are not protected.\nModel times vary by CPU. This does not repair flicker in the backend's own output.", "只运行选中的模型。PP-HumanSeg 和 YOLO 识别全身；YuNet 用柔边椭圆保护检测到的脸部。\nYuNet 可选 320、384 和 416 输入尺寸。小脸、侧脸或被遮挡的脸可能漏检；不保护头发和衣服。\n耗时取决于 CPU。本选项不修复后端输出本身的闪烁。"},
{"person model ready (PP-HumanSeg)", "人物模型已就绪 (PP-HumanSeg)"},
{"person model ready (YOLO11n-seg)", "人物模型已就绪 (YOLO11n-seg)"},
{"person model ready (YuNet (Face only))", "人物模型已就绪（YuNet，仅面部）"},

{"Face input size", "人脸输入尺寸"},
{"Full-frame YuNet input. Larger sizes can detect smaller faces but use more CPU time. Default 320. Changing size resets the face mask.", "YuNet 全画面检测的输入尺寸。较大尺寸有助于识别小脸，但 CPU 耗时更高。默认 320，切换后重置脸部蒙版。"},
