# Generate the AMD log identity for ordinary MSBuild/Visual Studio/CI builds.
# This identifies host source, not external SDKs, build options, or the DLL itself.
param(
    [Parameter(Mandatory = $true)][string]$ProjectDirectory,
    [Parameter(Mandatory = $true)][string]$OutputPath
)

$ErrorActionPreference = 'Stop'
function Get-SourceHash([string]$Path) {
    # Use .NET directly: MSBuild can inherit a PowerShell 7 PSModulePath that
    # prevents Windows PowerShell from auto-loading Get-FileHash's module.
    $stream = [System.IO.File]::OpenRead($Path)
    $hasher = [System.Security.Cryptography.SHA256]::Create()
    try {
        return [System.BitConverter]::ToString($hasher.ComputeHash($stream)).Replace('-', '').ToLowerInvariant()
    } finally {
        $hasher.Dispose()
        $stream.Dispose()
    }
}
$projectRoot = (Resolve-Path -LiteralPath $ProjectDirectory).Path.TrimEnd('\', '/')
$outputFile = [System.IO.Path]::GetFullPath($OutputPath)
$revision = 'unknown'
try {
    $git = Get-Command git -ErrorAction SilentlyContinue
    if ($git) {
        $candidate = & $git.Source -C $projectRoot rev-parse --short=12 HEAD 2>$null
        if ($LASTEXITCODE -eq 0 -and $candidate -match '^[0-9a-f]{12,40}$') {
            $revision = $candidate.Trim()
        }
    }
} catch {
    # Source archives and machines without Git still receive a content identity.
    $revision = 'unknown'
}

# Keep generated files and all normal intermediate directories out of the hash.
# In particular, resource_build_* changes on every Release build, and including
# our own output would make the source identity change on every invocation.
$extensions = @('.c', '.cc', '.cpp', '.h', '.hpp', '.inl', '.inc', '.hlsl', '.hlsli',
                '.vcxproj', '.props', '.targets', '.rc', '.def', '.cso', '.spv')
$manifest = New-Object 'System.Collections.Generic.List[string]'
Get-ChildItem -LiteralPath $projectRoot -File -Recurse | ForEach-Object {
    $relative = $_.FullName.Substring($projectRoot.Length + 1).Replace('\', '/')
    if ($_.Extension -in $extensions -and
        $relative -notmatch '(^|/)(x64|Win32|obj|Release|Debug|ReleaseDebug|\.vs)(/|$)' -and
        $_.Name -notlike 'resource_build_*' -and
        $_.FullName -ne $outputFile) {
        $hash = Get-SourceHash $_.FullName
        $manifest.Add($relative + ':' + $hash)
    }
}
$scriptHash = Get-SourceHash $PSCommandPath
$manifest.Add('tools/write-amd-graphics-source-id.ps1:' + $scriptHash)
$manifest.Sort([System.StringComparer]::Ordinal)
$sha = [System.Security.Cryptography.SHA256]::Create()
try {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes([string]::Join("`n", $manifest))
    $contentHash = [System.BitConverter]::ToString($sha.ComputeHash($bytes)).Replace('-', '').ToLowerInvariant()
} finally {
    $sha.Dispose()
}

$sourceId = $revision + '+host-src-' + $contentHash
$header = "// Generated by tools/write-amd-graphics-source-id.ps1; do not edit.`r`n" +
          "#pragma once`r`n#ifndef AMD_GRAPHICS_SOURCE_ID`r`n" +
          '#define AMD_GRAPHICS_SOURCE_ID "' + $sourceId + "`"`r`n#endif`r`n"
# Preserve the timestamp when content is identical, so incremental builds do not
# compile AmdPreSr.cpp again just because the identity target ran.
if (-not (Test-Path -LiteralPath $outputFile) -or
    [System.IO.File]::ReadAllText($outputFile) -ne $header) {
    [System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($outputFile)) | Out-Null
    [System.IO.File]::WriteAllText($outputFile, $header, [System.Text.Encoding]::ASCII)
}
Write-Output ('AMD graphics source: ' + $sourceId)
